kubernetes-sigs/controller-tools

PROJECT, cmd/controller-scaffold/cmd/api.go, cmd/controller-scaffold/cmd/project.go, pkg/scaffold/input/input.go, pkg/scaffold/project/boilerplate.go, pkg/scaffold/project/gopkg.go, pkg/scaffold/project/project.go, pkg/scaffold/project/project_suite_test.go, pkg/scaffold/project/project_test.go, pkg/scaffold/project/projectutil/projectutil.go, pkg/scaffold/scaffold.go, pkg/scaffold/scaffoldtest/scaffoldtest.go, test.sh, test/Gopkg.toml, test/PROJECT, test/vendor
> ok  	sigs.k8s.io/controller-tools/pkg/scaffold/project	0.068s	coverage: 97.1% of statements
=> Add pkg/scaffold/project tests

cmd/controller-scaffold/cmd/api.go, cmd/controller-scaffold/cmd/project.go, pkg/scaffold/controller/controller.go, pkg/scaffold/controller/controllertest.go, pkg/scaffold/project/project_test.go, pkg/scaffold/resource/resource.go, pkg/scaffold/resource/resource_suite_test.go, pkg/scaffold/resource/resource_test.go, pkg/scaffold/resource/typestest.go, pkg/scaffold/resource/version_suitetest.go, pkg/scaffold/scaffoldtest/scaffoldtest.go, test.sh, test/config/crds/creatures_v2alpha1_kraken.yaml, test/config/manager/creatures_role_rbac.yaml, test/config/manager/creatures_rolebinding_rbac.yaml, test/pkg/apis/addtoscheme_creatures_v2alpha1.go, test/pkg/apis/creatures/group.go, test/pkg/apis/creatures/v2alpha1/doc.go, test/pkg/apis/creatures/v2alpha1/kraken_types.go, test/pkg/apis/creatures/v2alpha1/kraken_types_test.go, test/pkg/apis/creatures/v2alpha1/register.go, test/pkg/apis/creatures/v2alpha1/v2alpha1_suite_test.go, test/pkg/controller/add_kraken.go, test/pkg/controller/firstmate/firstmate_controller.go, test/pkg/controller/firstmate/firstmate_controller_test.go, test/pkg/controller/frigate/frigate_controller_test.go, test/pkg/controller/kraken/kraken_controller.go, test/pkg/controller/kraken/kraken_controller_suite_test.go, test/pkg/controller/kraken/kraken_controller_test.go, test_dir.sh
- Fix issues with non-namespaced resources
- Add flags to scaffold api command to make it so it doesn't prompt the user for input
- Add tests for pkg/scaffold/resource to compare output from libraries to golden files under test/
- Update goldenfiles under test/ by rerunning the scaffolding commands
- Add script to populate golden file directory from scratch
- delete contents
- link vendor directory
- run scaffold project and apis
- run make
=> Tests for pkg/resource

cmd/crd/cmd/generate.go, cmd/crd/cmd/root.go, cmd/crd/main.go, pkg/crd/generator/generator.go, pkg/crd/util/util.go, pkg/internal/codegen/parse/apis.go, pkg/internal/codegen/parse/context.go, pkg/internal/codegen/parse/controllers.go, pkg/internal/codegen/parse/crd.go, pkg/internal/codegen/parse/index.go, pkg/internal/codegen/parse/parser.go, pkg/internal/codegen/parse/rbac.go, pkg/internal/codegen/parse/util.go, pkg/internal/codegen/types.go, pkg/scaffold/scaffold.go, pkg/util/util.go, test.sh, vendor/github.com/pkg/errors/.gitignore, vendor/github.com/pkg/errors/.travis.yml, vendor/github.com/pkg/errors/LICENSE, vendor/github.com/pkg/errors/README.md, vendor/github.com/pkg/errors/appveyor.yml, vendor/github.com/pkg/errors/errors.go, vendor/github.com/pkg/errors/stack.go
To address: https://github.com/kubernetes-sigs/kubebuilder/issues/273
=> Add CRD generation command

pkg/scaffold/controller/controller.go, test/pkg/controller/firstmate/firstmate_controller.go, test/pkg/controller/frigate/frigate_controller.go, test/pkg/controller/kraken/kraken_controller.go, test/pkg/controller/namespace/namespace_controller.go
Automatically add default annotations in scaffolding apis
=> Add default rbac annotation in resource

pkg/scaffold/project/gitignore.go, test/.gitignore
Otherwise this breaks build from a checkout
=> Don't gitignore generated files under vendor

pkg/scaffold/project/kustomize.go, pkg/scaffold/project/kustomize_image_patch.go, pkg/scaffold/project/makefile.go, test/Makefile, test/config/default/kustomization.yaml, test/config/default/manager_image_patch.yaml
Highlights:
- Enabled image patch in kustomization.yaml
- enabled image-url in Makefile targets
- Added `make deploy` target
=> added make deploy target with kustomize integration

cmd/controller-gen/main.go
fixes issue 328 in Kubebuilder repo
https://github.com/kubernetes-sigs/kubebuilder/issues/328
=> Skip openapi schema generation for map-type

pkg/scaffold/project/kustomize.go, test.sh, test/config/default/kustomization.yaml
Ref: https://github.com/kubernetes-sigs/kubebuilder/issues/385
=> fix kustomization.yaml

cmd/controller-gen/main.go, pkg/generate/internal/util.go, pkg/generate/rbac/manifests.go, pkg/generate/rbac/parser.go, pkg/generate/rbac/parser_test.go, pkg/generate/webhook/internal/client.go, pkg/generate/webhook/internal/client_test.go, pkg/generate/webhook/internal/manager.go, pkg/generate/webhook/manifests.go, pkg/generate/webhook/parser.go, pkg/generate/webhook/parser_test.go
kubernetes-sigs/kubebuilder#450 shows how the annotations and generated manifest looks like.
This PR depends on #101
=> Gen webhook manifests

pkg/crd/generator/testData/config/crds/fun_v1alpha1_toy.yaml, pkg/crd/generator/testData/pkg/apis/fun/v1alpha1/toy_types.go, pkg/internal/codegen/parse/crd.go, pkg/internal/codegen/parse/util.go, pkg/internal/codegen/parse/util_test.go
=> logic to control additional printer columns

examples/godocbot/Dockerfile, pkg/crd/generator/testData/Dockerfile
Parallel to https://github.com/kubernetes-sigs/kubebuilder/pull/500
=> Dockerfile: move manager to /, from /root/

.github/PULL_REQUEST_TEMPLATE/breaking_change.md, .github/PULL_REQUEST_TEMPLATE/bug_fix.md, .github/PULL_REQUEST_TEMPLATE/compat_feature.md, .github/PULL_REQUEST_TEMPLATE/docs.md, .github/PULL_REQUEST_TEMPLATE/other.md, .github/pull_request_template.md
The templates are copied from controller-runtime repo as-is.
=> :running: added PR templates

pkg/internal/codegen/parse/util.go, pkg/webhook/parser_test.go
=> [Bug fix] Remove debug info, fix error message in webhook

pkg/internal/codegen/parse/crd.go
Special types and upstream kube types should get tag support as well. In 1.14 we will get `nullable` support (https://github.com/kubernetes/kubernetes/pull/74804) and that should be applied to those types as well.
=> crd-gen: apply tags to special types, kube types and maps as well

cmd/crd/cmd/generate.go, pkg/crd/generator/generator.go
Reverts kubernetes-sigs/controller-tools#144
Since this introduced regression https://github.com/kubernetes-sigs/controller-tools/issues/148
=> Revert "✨Add flags to customize API path and contexts"

pkg/internal/codegen/parse/crd.go
Signed-off-by: Tamal Saha <tamal@appscode.com>
=> Fix OpenAPI type for resource.Quantity fields

cmd/controller-gen/main.go
Hi,
I fixed controller-gen rbac example.
=> 🐛 Fix rbac example

pkg/loader/refs.go
This avoids race condition which may happen when multiple goroutines try
to modify the `checkedPackages` field of TypeChecker simultaneously.
Fix: https://github.com/kubernetes-sigs/controller-tools/issues/238
**Performance concerns:**
I measured the time consumed by the `TypeChecker.Check` method on `kubebuilder/cronjob/api/v1` package with and without this change. In both cases, the time consumption is about 130 ms. One explanation for the similar performance is that the race condition does not happen at all during my test.
=> Add a `sync.Mutex` field into TypeChecker

pkg/rbac/parser.go
To minimize the generated rules in role.yaml, the following optimizations are added:
* remove duplicates from every field of rbac.Rule
* sort items in every field of rbac.Rule
This should fix https://github.com/kubernetes-sigs/kubebuilder/issues/743
=> Merge rules in config/rbac/role.yaml

pkg/crd/schema.go, pkg/crd/testdata/cronjob_types.go, pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Fix: https://github.com/kubernetes-sigs/controller-tools/issues/213
=> Add support for arrays as map values into pkg/crd

pkg/loader/loader.go
Due to a flawed assumption about dummy packages vs normal packages in
the partial type checker, it was possible to have a data race on thetypecheck data when one package dependended on a given package, and
another had its dependency on that package filtered out.
Makes sure to lock when populating the dummy package data to avoid this.
=> :bug: Avoid data race on package type data

pkg/crd/gen.go, pkg/crd/zz_generated.markerhelp.go
This PR adds command line help for `maxDescLen` parameter.
=> :book: generate help for maxDecLen commandline parameter

pkg/webhook/parser.go
**NOTE** This PR is not ready for review until #276 merges.
I was independently updating deps to kube 1.16 per the request of @sttts and only near completion noticed #276.  Since I had already refactored the code in keeping with a [request](https://github.com/kubernetes-sigs/controller-tools/pull/276#discussion_r315394569) by @DirectXMan12, I'm posting those changes on top of #276 in case they are useful.
=> :sparkles: Factor code common to both types of webhooks into methods

.github/pull_request_template.md
Such a tiny detail, I'm wondering if it's worth spending people time on it.
Sorry!
=> Add missing trailing : to :sparkles: in the PR template

pkg/crd/markers/zz_generated.markerhelp.go, pkg/crd/testdata/cronjob_types.go, pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Adds pattern validator test, both to ensure it's working and also as an example. 
/assign @sttts @DirectXMan12
=> 🏃 Add pattern validator test

pkg/crd/known_types.go, pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Signed-off-by: Tamal Saha <tamal@appscode.com>
Fixes #304
This is an alternative for https://github.com/kubernetes-sigs/controller-tools/pull/312 .
=> :bug: Update known_types to add x-kubernetes-int-or-string for intStr

OWNERS, OWNERS_ALIASES
Signed-off-by: Vince Prignano <vincepri@vmware.com>
=>  🏃Add vincepri to maintainers

pkg/webhook/parser.go
Signed-off-by: Vince Prignano <vincepri@vmware.com>
=> ✨ Add support for MatchPolicy in webhook marker

pkg/crd/flatten.go
=> Resolve reference in order to remove $ref which is not supported by k8s

pkg/rbac/parser.go, pkg/rbac/testdata/controller.go, pkg/rbac/testdata/role.yaml, pkg/rbac/zz_generated.markerhelp.go
This makes it possible to generate policy rules restricted to specific
instances.
Fixes #401
=> ✨ Add new resourceNames field in RBAC marker

go.mod, go.sum, pkg/crd/parser_integration_test.go, pkg/crd/spec.go, pkg/crd/testdata/plural/plural.example.com_testquotas.yaml, pkg/crd/testdata/plural/types.go
* 🐛 Generate plural words for Kind correctly
=> 🐛 Generate plural words for Kind correctly (#522)

OWNERS_ALIASES
=> 🏃add joelanford to controller-tools-maintainers

OWNERS_ALIASES
Adds alvaroaleman to the maintainers.
/assign @vincepri
=> :running: Add alvaroaleman to maintainers

pkg/crd/markers/topology.go
Signed-off-by: Tamal Saha <tamal@appscode.com>
=> 🏃 Improve error message for list or map type

README.md
=> 🏃 add go reference badge

.github/dependabot.yml
I notice that the dependabot PRs were manually be changed to add :seedling: tag.  We can add that to the commit message.
=> :seedling: Add :seedling: to dependabot commit message

OWNERS_ALIASES
=> ✨ Update and sync owners file w/ CR runtime

OWNERS_ALIASES
This was missed in my previous cleanup
=> 🌱 Re-add list of emeritus maintainers

.github/workflows/tools-releases.yml, envtest-releases.yaml, hack/envtest/update-releases.sh
=> :seedling: Automatically release, fixup selfLink in camelCase

envtest-releases.yaml
=> 🌱 Promotion of envtest release for Kubernetes v1.28.3

go.mod, pkg/crd/known_types.go
This PR uses the `ptr` package.
=> :running: use ptr package

pkg/crd/markers/validation.go
📖 Fix a typo in comment in validation.go (Knwon -> Known)
=> 📖 Fix a typo in comment in validation.go

Makefile
=> 🏃 Enforce go mod tidy via "test" presubmit

.github/workflows/golangci-lint.yml, .github/workflows/tools-releases.yml, README.md
=> 🏃 Rename default branch to main

.github/workflows/verify.yml, hack/verify-pr-title.sh
Same as https://github.com/kubernetes-sigs/controller-runtime/pull/2944
=> 🏃 Verify PR titles with shell script

.github/pull_request_template.md
Update the PR template to match the valid icons.
=> 📖 github: update PR template

README.md
=> 📖 Fix compatibility table

.github/workflows/release.yaml, .github/workflows/tools-releases.yml
The current action hits https://github.com/softprops/action-gh-release/issues/556
=> 🌱 Downgrade gh-release action

README.md
=> 📖 Add v0.17 to compatibility table

envtest-releases.yaml
Generated via the script on https://github.com/kubernetes-sigs/controller-tools/pull/1113
=> 🌱 Promotion of envtest release for Kubernetes v1.33.0-alpha.2

envtest-releases.yaml
=> 🌱 Promotion of envtest release for Kubernetes v1.33.0

envtest-releases.yaml
=> 🌱 Promotion of envtest release for Kubernetes v1.34.0-alpha.1

.github/workflows/golangci-lint.yml
Sync controller-runtime .golangci.yaml
ref: https://github.com/kubernetes-sigs/controller-runtime/pull/3318
=> 🌱chore: Update golangci-lint version to v2.4.0

envtest-releases.yaml
=> 🌱 Promotion of envtest release for Kubernetes v1.34.1
