- cmd/controller-gen/main.go
- cmd/rbac/main.go
- pkg/generate/rbac/manifests.go
- pkg/generate/rbac/parser.go
- pkg/generate/rbac/parser_test.go
Note: need feedback specifically about the pkg and command's location. 
Added `rbac` new commandline tool and `rbac` pkg under `pkg/generate/rbac` for generating RBAC manifests.  It scans the Go source files under given input-dir and parses the RBAC annotations and generates the RBAC manifests. The annotations could be anywhere in the Go files not necessarily tied to a Type or Function (Thats one reason `gengo` wasn't useful). Parser uses `Go` standard packages (ast, parser) instead of `gengo` because requirements were very simple. 
Realized that we will have to generate RBAC annotations while scaffolding the resources so that this tool can generate RBAC manifests.
> added rbac manifests generation pkg and CLI

- cmd/controller-gen/main.go
- pkg/generate/rbac/manifests.go
enabled `rbac` generation in `controller-gen all` run. 
Will be using this command to generate rbac/crd manifests using `go generate` directive in the generated project.
> controller-gen: added rbac generation

- pkg/scaffold/controller/controller.go
- test/config/rbac/rbac_role.yaml
- test/pkg/controller/firstmate/firstmate_controller.go
- test/pkg/controller/frigate/frigate_controller.go
- test/pkg/controller/kraken/kraken_controller.go
Found this bug during testing today where RBAC manifests for CRD types didn't include fully qualified api-group-name (with domain suffix etc.) and also discovered `resources` were not being pluralized properly.
> fixed api-group and resource field in RBAC annotation

- generated_golden.sh
- pkg/scaffold/controller/controller.go
- pkg/scaffold/controller/controllertest.go
- pkg/scaffold/project/project_test.go
- test/PROJECT
- test/config/crds/crew_v1_firstmate.yaml
- test/config/crds/policy_v1beta1_healthcheckpolicy.yaml
- test/config/crds/ship_v1beta1_frigate.yaml
- test/config/rbac/rbac_role.yaml
- test/config/samples/creatures_v2alpha1_kraken.yaml
- test/config/samples/crew_v1_firstmate.yaml
- test/config/samples/policy_v1beta1_healthcheckpolicy.yaml
- test/config/samples/ship_v1beta1_frigate.yaml
- test/pkg/apis/addtoscheme_policy_v1beta1.go
- test/pkg/apis/creatures/v2alpha1/doc.go
- test/pkg/apis/crew/v1/register.go
- test/pkg/apis/policy/group.go
- test/pkg/apis/policy/v1beta1/doc.go
- test/pkg/apis/policy/v1beta1/healthcheckpolicy_types.go
- test/pkg/apis/policy/v1beta1/healthcheckpolicy_types_test.go
- test/pkg/apis/policy/v1beta1/register.go
- test/pkg/apis/policy/v1beta1/v1beta1_suite_test.go
- test/pkg/apis/ship/v1beta1/doc.go
- test/pkg/apis/ship/v1beta1/register.go
- test/pkg/controller/add_healthcheckpolicy.go
- test/pkg/controller/firstmate/firstmate_controller.go
- test/pkg/controller/healthcheckpolicy/healthcheckpolicy_controller.go
- test/pkg/controller/healthcheckpolicy/healthcheckpolicy_controller_suite_test.go
- test/pkg/controller/healthcheckpolicy/healthcheckpolicy_controller_test.go
- test/pkg/controller/kraken/kraken_controller.go
bind resource for controller based on whether resource is created.
1) If resource is created in project, bind with created resource.
2) If resource not created, gkv matches core types, bind with core-types.
3) Else, using specified resourcePath by flag --resource-pkg-path (TODO)
Fix issues:
https://github.com/kubernetes-sigs/kubebuilder/issues/342
https://github.com/kubernetes-sigs/kubebuilder/issues/335
https://github.com/kubernetes-sigs/kubebuilder/issues/338
> Fix domain resource issues in controller

- pkg/crd/generator/testData/config/crds/fun_v1alpha1_toy.yaml
- pkg/crd/generator/testData/pkg/apis/fun/v1alpha1/toy_types.go
- pkg/internal/codegen/parse/crd.go
- pkg/internal/codegen/parse/util.go
- pkg/internal/codegen/parse/util_test.go
- pkg/internal/codegen/types.go
- Add Scale Subresource tag validation for parsing CRD.
- Usage to enable scale subresource in CRD:
1) add tag close above Resource struct, like:
```golang
// +kubebuilder:subresource:scale:specpath=.spec.replica,statuspath=.status.replica,selectorpath=.jsonpath
```
`specpath`, `statuspath`, `selectorpath` key values, represents for JSONPath of **SpecReplicasPath**,  **StatusReplicasPath**,  **LabelSelectorPath** separately.
`specpath` and `statuspath` must be provided. `selectorpath` is optional
2) Modify corresponding Spec and Status struct in types.
3) Modify types_test.go files accordingly.
https://github.com/kubernetes-sigs/kubebuilder/issues/303
> Feature: support scale sub resource by tag in controller-tools

- pkg/scaffold/scaffold.go
- test.sh
This PR is doing the same thing as https://github.com/kubernetes-sigs/controller-runtime/pull/126
> gas linter has been renamed to gosec

- pkg/crd/generator/testData/config/crds/fun_v1alpha1_toy.yaml
- pkg/internal/codegen/parse/crd.go
- test/config/crds/creatures_v2alpha1_kraken.yaml
- test/config/crds/crew_v1_firstmate.yaml
- test/config/crds/policy_v1beta1_healthcheckpolicy.yaml
- test/config/crds/ship_v1beta1_frigate.yaml
k8s 1.11 rejects CRDs with type property at the root if status sub-resources enabled.
This change drops the type field for CRD at the root level.
https://github.com/kubernetes/kubernetes/issues/65293
https://github.com/kubernetes/kubernetes/pull/65357
> removed type field from crd validation schema

- pkg/crd/generator/testData/config/crds/fun_v1alpha1_toy.yaml
- pkg/crd/generator/testData/pkg/apis/fun/v1alpha1/toy_types.go
- pkg/internal/codegen/parse/crd.go
- pkg/internal/codegen/parse/util.go
- pkg/internal/codegen/types.go
fixes https://github.com/kubernetes-sigs/controller-runtime/issues/151
> crd: add finalizers support in CRD generation

- pkg/internal/codegen/parse/crd.go
Add a special case for the unstructured.Unstructured type from apimachinery. This can
be arbitrary JSON/YAML, so, like ObjectMeta, set type to just 'Object'
This is needed for the ClusterBundle, which relies heavily on unstructured objects.
> Special case 'unstructured'

- pkg/internal/codegen/parse/util.go
- pkg/internal/codegen/parse/util_test.go
While not part of the OpenAPI spec, "date" is the type used by the
defaulted field "age" to present a relative value (e.g 4h ago).
The full list of allowable types exists at https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation/validation.go#L38
> Add support for the date type in +printcolumn

- pkg/crd/generator/testData/config/crds/fun_v1alpha1_toy.yaml
- pkg/crd/generator/testData/pkg/apis/fun/v1alpha1/toy_types.go
- pkg/internal/codegen/parse/crd.go
Fix https://github.com/kubernetes-sigs/kubebuilder/issues/442
> Handle "intstr.IntOrString" use case for the generated openAPI validation

- pkg/crd/generator/testData/config/crds/fun_v1alpha1_toy.yaml
- pkg/crd/generator/testData/pkg/apis/fun/v1alpha1/toy_types.go
- pkg/internal/codegen/parse/crd.go
- pkg/internal/codegen/parse/util.go
Fix #102 
List of assumptions while creating this PR.
1.  Not including `+kubebuilder` and `+optional` comments in the description.
2.  The `description` field will not be created if there are no comments above the field in the type definition.
> Include description in the OpenAPI schema under fields property

- pkg/crd/generator/testData/config/crds/fun_v1alpha1_toy.yaml
- pkg/crd/generator/testData/pkg/apis/fun/v1alpha1/toy_types.go
- pkg/internal/codegen/parse/crd.go
- pkg/internal/codegen/parse/util.go
-  What does this do, and why do we need it?
This PR fix the description field generation for all types of fields under `Openschema API`.
For more details, please go through this issue #116
> :bug: Fix description generation to work for all types of fields

- cmd/type-scaffold/main.go
- pkg/typescaffold/resource.go
- pkg/typescaffold/scaffold.go
- pkg/typescaffold/scaffold_test.go
This extracts KubeBuilder's object scaffolding logic into a separate
command.  Creating the basic structure for Kubernetes objects is a
non-opinionated task, so it can be reused for other purposes
(incrementally adding types to files, non-KubeBuilder scaffolding
projects, etc).
> :sparkles: Object scaffolding logic from KubeBuilder

- pkg/crd/generator/testData/config/crds/fun_v1alpha1_toy.yaml
- pkg/crd/generator/testData/pkg/apis/fun/v1alpha1/toy_types.go
- pkg/internal/codegen/parse/crd.go
fix https://github.com/kubernetes-sigs/kubebuilder/issues/404
current implement  only supports single shortname, however, in CRD, `shortName` is an array.  this pr create a new annotation to help generating shortnames. 
Signed-off-by: magicsong <magicsong@yunify.com>
> ✨add shortnames annotation

- pkg/internal/codegen/parse/crd.go
Previously when generating a validation schema for metav1.Duration fields, the field would be marked as type `object` instead of `string` as set here: https://github.com/kubernetes/apimachinery/blob/4b4ea28f279089e0cfafcc2d47479a5bd1a0964f/pkg/apis/meta/v1/duration.go#L56
Similar to how controller-tools currently handles metav1.Time, I've added an exception for metav1.Duration so this will be correctly typed 😄
> 🐛 Fix OpenAPI type for metav1.Duration fields

- pkg/crd/generator/testData/config/crds/fun_v1alpha1_toy.yaml
- pkg/crd/generator/testData/pkg/apis/fun/v1alpha1/toy_types.go
- pkg/internal/codegen/parse/crd.go
- pkg/internal/codegen/parse/util.go
This adds a `+kubebuilder:singular=foo` tag to specify singular names for CRDs if desired
> ✨ Add support for CRD singular name

- pkg/crd/generator/testData/config/crds/fun_v1alpha1_toy.yaml
- pkg/crd/generator/testData/pkg/apis/fun/v1alpha1/toy_types.go
- pkg/internal/codegen/parse/crd.go
Adds the "format" validation key to the generated schema whenever it is
added explicitely to a type by an annonation.
Closes #123
> :bug: Fixes missing format validation key

- pkg/crd/generator/testData/config/crds/fun_v1alpha1_toy.yaml
- pkg/crd/generator/testData/pkg/apis/fun/v1alpha1/toy_types.go
- pkg/internal/codegen/parse/crd.go
This commit removes the "format" key from array objects since any format annotations on arrays are assumed to be applicable to the array items rather than to the array itself.  Byte arrays are handled as a special case since they are represented as byte strings in the CRD YAML rather than actual arrays.
Closes #141
I wasn't sure how long it would take to get PR #140 merged so I went ahead and created this PR on top of the fix for PR #140 since there was some overlap in the test data.   When PR #140 merges I will gladly rebase this PR to exclude the other commit.
> :bug: Removes extraneous "format" key from array objects

- cmd/crd/cmd/generate.go
- pkg/crd/generator/generator.go
We have some use cases where API types are defined in a different package or location than the default `pkg/apis` currently hardcoded. For example, we have vendored types in an API library that correspond to CRDs in multiple different repos; this would allow us to establish a workflow such as 
1. Update API types in library
2. Bump that library in specific CRD repos
3. Generate new CRDs in those repos (wherein those types exist under, eg, `vendor/org/library/some-api/v1/`)
By specifying a known directory and context, we can still use this tool with only minor changes (the optional flags added in this PR) and this gives us more ability to customize it to our use cases.
I'm aware that we could accomplish something similar with `--output-dir`, by going in the opposite direction and running …
> ✨Add flags to customize API path and contexts

- pkg/crd/generator/testData/config/crds/fun_v1alpha1_toy.yaml
- pkg/crd/generator/testData/pkg/apis/fun/v1alpha1/toy_types.go
- pkg/internal/codegen/parse/crd.go
Support json fields that have numbers. E.g. `S3`. 
Fix #150 
Tests done:
1. using alphanum as json field names, and attach `+kubebuilder:validation` validation to the field elements.
e.g. 
> S3 LoadBalancerAccessLogsS3Attributes `json:"s3,omitempty"`
1. The generated openAPIV3Schema in CRD contains the expected s3 field, and the validation exists.
1. Install the CRD into an k8s v1.11.5 cluster, and tested the validation works by creating success/fail CRs.
> 🐛support alphanum json field in json validation

- pkg/internal/codegen/parse/crd.go
RawExtension is the canonical type for embedded kube objects, at least when working with typed clients. From the OpenAPI point of view it is like Unstructured.
> crd-gen: add RawExtension support

- pkg/internal/codegen/parse/index.go
This change improves pluralisation on resource names in CRDs (e.g. indexes -> indices).
[Kubebuilder](https://github.com/kubernetes-sigs/kubebuilder) that depends on this project uses the default rule set for controller code generation, and so it can generate CRDs and controllers inconsistently. 
The main motivation of this fix is to address the issue.
> :warning: Change to use the default rule set for Pluralize.

- cmd/controller-gen/main.go
- pkg/rbac/manifests.go
**What type of PR is this?**
/kind feature
/sig api-machinery
/priority important-longterm
**What this PR does / why we need it**:
Introduces some configuration options for RBAC generation that allows to bind cluster roles to custom service accounts instead of `"default"` in `"system"` and also allows to specify the name of the output files.
**Which issue(s) this PR fixes**:
Fixes #145 
Fixes #146
**Special notes for your reviewer**:
**Does this PR introduce a user-facing change?**:
```release-note
The default output files have been changed from "rbac_role.yaml" and "rback_role_binding.yaml" to "manager_role.yaml" and "manager_role_binding.yaml".
```
> Configuration options

- pkg/internal/codegen/parse/crd.go
- testData/config/crds/fun_v1alpha1_toy.yaml
OneOf is a dangerous junctor (like not) because it is not monotonic. It leads to strange corner cases like `42` being a float and an integer. OneOf with `number` and `integer` will not validate `42`.
In general, rule of thumb is to avoid `OneOf` where possible.
Due to the bad properties of OneOf we cannot publish OneOf types via the swagger spec, i.e. we have to filter out those types in CRD openapi publishing (alpha in 1.14, https://github.com/kubernetes/kubernetes/pull/71192).
Luckily, `AnyOf` does the same for this purpose here and is the way to go for the upper reasons.
> crd-gen: fix intOrString type

- Gopkg.lock
- Gopkg.toml
- vendor/k8s.io/api/core/v1/generated.proto
- vendor/k8s.io/api/core/v1/types.go
- vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
- vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
- vendor/k8s.io/apimachinery/pkg/runtime/codec.go
✨
It is in the best interests of any k8s API consumer that we always vendor in the latest patch release of a minor version.
As controller-tools acts as a source of k8s-dependencies for cluster-API and its providers, best practices mandate that we update the versions at the root so that they percolate down to the Cluster API providers. If this change is not accepted, we would be forced to use override deps.
> ✨ update the kubernetes dependencies to the latest patch release of 1.13 -  1.13.4

- pkg/webhook/manifests.go
Fixes https://github.com/kubernetes-sigs/controller-tools/issues/154
> :bug: skip generating webhooks when no markers defined

- cmd/controller-gen/main.go
- cmd/crd/cmd/generate.go
- pkg/crd/generator/generator.go
Re-adds the changes that were reverted in https://github.com/kubernetes-sigs/controller-tools/pull/169, with the key change that `APIsPath` has a default of `pkg/apis` validated in the `"crdgenerator.Generator".ValidateAndInitFields()` method which should be called by all commands using that type
> Add APIsPath and APIsPkg crd generator variables w/ defaults

- pkg/crd/generator/generator.go
When using `Generator` multiple times, ex. in tests, the working directory changes between test function invocations. Deferring a chdir fixes this issue.
> :sparkles: pkg/crd/generator: defer chdir back to calling dir

- pkg/crd/generator/generator.go
https://github.com/kubernetes-sigs/controller-tools/commit/626472cffd8eac5000961685a6c15b5942f6d36f created a dependency on a PROJECT file, this removes that dependency for the CRD generator specifically if these values are manually set
> Remove dependency on PROJECT file for CRD generator

- pkg/crd/v2/crd.go
- pkg/crd/v2/definition_checker.go
- pkg/crd/v2/definition_pruner.go
- pkg/crd/v2/embed.go
- pkg/crd/v2/flattener.go
- pkg/crd/v2/generator.go
- pkg/crd/v2/multiversion.go
- pkg/crd/v2/parser.go
- pkg/crd/v2/types.go
- pkg/crd/v2/utils.go
In this PR, I am contributing changes from: https://github.com/redborian/go-types-to-jsonschema. It uses built-in go types to parse a given go package into JSON schema. This has contributions from both myself as well as @mengqiy.
These changes will go to `crdgenerator` feature branch. The generator has not been wired up with commands. Once this PR goes through, we will look at wiring it up. Also, it needs test coverage that we will be adding later in the feature branch. Once we get the green light, we will merge the feature branch into master branch.
> ⚠Rewriting CRD generator to use built-in go type inferences

- pkg/webhook/generator.go
- pkg/webhook/generator_test.go
drop annotation in webhook manifests generator since the annotation will be done in kubebuilder.
> drop annotation in webhook manifests generator

- testData/Dockerfile
- testData/Makefile
- testData/PROJECT
- testData/cmd/manager/main.go
- testData/go.mod
- testData/pkg/apis/addtoscheme_fun_v1alpha1.go
- testData/pkg/apis/fun/v1alpha1/doc.go
- testData/pkg/apis/fun/v1alpha1/register.go
It appears that the testData/ directory was moved to its current location in a different PR but the previous  path was not modified in a few files. This causes `go get sigs.k8s.io/controller-tools` to fail.
With this fix, the mentioned command will work. I noticed that even with these fixes, `make all` fails but I think that is out of scope for this PR.
> :bug: Fix import path for references to testData/

- pkg/crd/generator/generator.go
- pkg/crd/util/util.go
- pkg/internal/codegen/parse/apis.go
- pkg/webhook/generator.go
- pkg/webhook/manifests.go
- pkg/webhook/writer.go
Fixes #152, enables Kubebuilder Windows releases.
> 🐛 fix windows filepath compatibility

- pkg/crd/gen.go
- pkg/crd/markers/crd.go
- pkg/crd/spec.go
This introduces two fixes for generated CRDs:
- populate the status slices so that they don't fail client-side validation
- allow producing a "trivially versioned" CRD that's compatible with Kubernetes 1.11+ instead of 1.13+
- make the `printcolumn` fields optional when appropriate
> :bug: Fix incompatible CRDs

- pkg/crd/gen.go
- pkg/genall/genall.go
- pkg/rbac/parser.go
- pkg/webhook/parser.go
This PR does 2 things:
- support writing multiple webhooks in one file
- add defaulting to admission webhook configurations
- work around the "required" caBundle field
> :sparkles: write multiple webhooks in one file and add defaulting

- pkg/crd/gen.go
- pkg/loader/refs.go
The ref checker would panic on missing imports before.  Now, we just add
an error and continue instead.
> :bug: Fix panic on missing import in ref checker

- pkg/crd/markers/crd.go
This change adds support for storage version marker to indicate which version type to mark for storage.
Note: I would like to double check the name for the marker, so keeping it "do-not-merge".
> :sparkles: CRD storage version marker

- pkg/crd/markers/validation.go
Kubernetes 1.14 has support for nullable properties. This PR adds a `+nullable` tag in analogy to `+optional`.
Before this compiles, we have to bump to Kubernetes 1.14 libraries.
> Support 1.14 +nullable tag

- OWNERS
- OWNERS_ALIASES
I'm doing some org/repo-wide OWNERS parsing, an empty alias is not valid
> ✨ controller-tools-maintainers is an empty alias

- pkg/markers/collect.go
- pkg/markers/markers_suite_test.go
We have special handling to skip end-of-line (same-line) comments while
collecting. However, when such a comment is also the last comment in the
file, we have to take special care, because it'll be associated with a
higher-level AST construct, but we may continue traversing to handle
special cases, so we have to take care to acknowlege that we've reached
the end of the file.
Fixes #212
> :bug: Ensure same-line last-comment case is handled

- pkg/deepcopy/traverse.go
Previously, only the first member of a struct was copied with pass-by-reference.
> 🐛 Generate deepcopy for all struct members

- pkg/crd/markers/crd.go
Add a crd resource scope marker to allow generation of cluster scoped resources.
This change is backwards compatible (absence of the scope marker results in an
empty scope).
This also allows for explicit scoping of namespaced resources should the user so
desire (fixes https://github.com/kubernetes-sigs/controller-tools/issues/214).
> ✨ crd: add a resource scope marker

- pkg/crd/markers/package.go
- pkg/crd/markers/validation.go
- pkg/crd/parser.go
- pkg/crd/schema.go
This introduces a `// +kubebuilder:validation:[Required/Optional]` marker which can be applied to both packages and fields. Placing it at the package level determines the default requirement for fields in that package (ie, a package marked with `// +kubebuilder:validation:Optional` will assume no fields are required unless specifically marked with `// +kubebuilder:validation:Required`).
If no package-level tag is set, this defaults to the current behavior of assuming all fields not tagged with `omitempty`, `inline`, or (now) `// +kubebuilder:validation:Optional` are required, so this change doesn't break current use cases.
> Add ability to set default field requirement status

- cmd/controller-gen/main.go
- pkg/rbac/manifests.go
Fixes a bug that is introduced in https://github.com/kubernetes-sigs/controller-tools/pull/147/files.
RbacOptions should be the same as https://github.com/kubernetes-sigs/controller-tools/blob/v0.1.10/cmd/controller-gen/main.go#L60-L61
Also revert the file name change, though it's not a breaking change. But the user can notice it.
> :bug: ensure defaults are set for controller-gen all

- pkg/crd/markers/validation.go
- pkg/crd/parser_integration_test.go
- pkg/crd/testdata/README.md
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Currently the `+optional` and `+nullable` markers don't work. I've fixed `optional` by making sure the `FieldOnlyMarkers` slice that was added in https://github.com/kubernetes-sigs/controller-tools/pull/211 actually gets added to `AllDefinitions`. In the current code, `+nullable` would actually only be recognized as `+kubebuilder:validation:Nullable=true`, so I'm updating this to be more consistent with what's expected for that marker.
However, I still can't get nullable to be generated in the output CRD, so I would appreciate some input on this
> 🐛Add FieldOnlyMarkers to AllDefinitions and update Nullable

- pkg/crd/markers/crd.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
- test.sh
Fix: https://github.com/kubernetes-sigs/controller-tools/issues/239
This PR also adds `-race` flag into `go test`
This should unblock https://github.com/kubernetes-sigs/kubebuilder/pull/763
> Make the `Path` field of the "+kubebuilder:resource" marker optional

- pkg/crd/known_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Reverts kubernetes-sigs/controller-tools#254
embedded objectmeta gets generated incorrectly now -- you can no longer specify labels, annotations, etc.
> Revert ":bug: special-casing metav1.ObjectMeta."

- cmd/controller-gen/main.go
- pkg/crd/markers/validation.go
- pkg/crd/testdata/README.md
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
- pkg/genall/help/pretty/help.go
This fixes a number of minor CLI help issues, including #261, as well as other minor nits.
It also fixes a regression around dual field/type CRD validation marker registration introduced by #248, which happens to directly manifest in help output, but will actually show up in generation as well.
> :bug: CLI Help issues and Marker Registration Regression

- PROJECT
IIRC this file was used by the example project a long time ago.
> :running: drop the useless PROJECT file

- pkg/crd/known_types.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
This brings the handling of k8s.io/apimachinery/pkg/apis/meta/v1/MicroTime in sync with k8s.io/apimachinery/pkg/apis/meta/v1/Time.
This resolves issue #270.
> ✨ Correctly format metav1.MicroTime as date-time

- pkg/crd/schema.go
This fixes an obvious typo encountered while using kubebuilder.
> ✨ Fix "encountered" typo in error message

- pkg/crd/spec.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
According to the kubernetes CRD validation, we need to make sure that the `Version` field always matches the first version in the versions list.  If that changes, we have to explicitly set the version field, since the defaulting will have pointed it at a different version on initial creation.
Fixes: https://github.com/kubernetes-sigs/controller-tools/issues/236
> Sort the CRD Versions in the generated CRD and set `crd.Spec.Version` explicitly

- Gopkg.lock
- pkg/crd/crd_spec_test.go
- pkg/crd/spec.go
The Kube API server requires that information common to all versions of
a CRD be collapsed into the top-level fields in v1beta1, since not doing
so would create ambiguity when round-tripping through the upcoming v1
version (which doesn't have top-level fields).  This makes sure we
collapse things.
> :bug: Collapse Common CRD Version Info

- pkg/crd/gen.go
So this fixes a very niche parsing issue:
```go
type noNotify struct{ error }
```
That parses as a field, but it has no package because it's a core type I think? Not 100% sure but it definitely causes a segfault :)
> 🐛 Handle the error type in crd gen

- pkg/crd/desc_visitor.go
- pkg/crd/desc_visitor_test.go
- pkg/crd/gen.go
- pkg/crd/parser_integration_test.go
- pkg/crd/spec.go
This PR adds support for limiting the description length for fields in OpenAPI Schema. It introduces a parameter `maxDescLen` for CRD generator. 
- Default value (0) means keep the description as-is for backward compatibility
- Negative value (-1) means drop the description field completely
- Positive (n) value will truncate the description to closest sentence boundary if description exceeds `maxDescLen`.
fixes https://github.com/kubernetes-sigs/kubebuilder/issues/906
> Limiting description of fields in CRD's OpenAPI Schema

- pkg/crd/markers/crd.go
- pkg/crd/markers/zz_generated.markerhelp.go
Adds a new marker that allows excluding particular CRD versions from the generated CRD output.
This is specifically useful to me in order to support having a stable 'internal' version that is used for a basis for conversion (we prefer to define this instead of using an external version as our 'hub' as we don't want to have to rewrite older conversion functions as we deprecate APIs 😄).
For more context, see #307
> ✨ Add skipversion marker to selectively exclude CRD versions

- pkg/crd/known_types.go
I think this fixes #301 . Basically treat `unstructured.Unstructured` type exactly same with `RawExtension`. 
Known packages are referred as:
```
// KnownPackages overrides types in some comment packages that have custom validation
// but don't have validation markers on them (since they're from core Kubernetes).
```
And I think we might be able to treat Unstructured like core k8s types because of the statement in  https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructured.go#L31 
But I don't really have a strong opinion on this.
> Treat unstructured.Unstructured type as known type.

- pkg/crd/spec.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
A CRD's ListKind and Singular names are not added by default, but are easy to infer from group data and therefore should be set by default.
> :sparkles: pkg/crd/spec.go: set default ListKind and Singular CRD names

- pkg/crd/schema.go
This PR is to address the request made the following:
- https://github.com/kubernetes-sigs/kubebuilder/issues/921#issuecomment-527563284
- https://github.com/kubernetes-sigs/kubebuilder/pull/975#issuecomment-527563813
I didn't mention `resource.Quantity` in the changes because I saw no sign of it in `builtinToType`. Please let me know if I've missed something and thanks!
> 📖Update builtinToType comments to explain support for int32 and int64

- pkg/crd/crd_spec_test.go
- pkg/crd/spec.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
This fixes an issue where version-specific fields are not properly promoted to their top-level `.spec` equivalents when there is only one version defined in `.spec.versions`.
> :bug: promote version-specific CRD fields when only one version

- pkg/markers/parse.go
- pkg/markers/parse_test.go
Maps in markers always have string keys, and may have any argument type, including
nested maps, slices, etc.
"Guessed" maps are always non-uniform (i.e. key of AnyType), since
they're frequently used to represent objects in JSON form.
They syntax looks like:
```
//+this:is:a:map={"text": "abc", len: 33}
```
> support maps in marker marker parsing

- pkg/crd/markers/doc.go
- pkg/crd/markers/validation.go
- pkg/crd/markers/zz_generated.markerhelp.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
- pkg/markers/parse.go
- pkg/markers/parse_test.go
- test.sh
**NOTE:** This PR is not ready for review until #329 merges.
Kube 1.16 adds beta support [for providing default values for fields](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#defaulting) in a CRD schema. This PR adds a marker that supports specifying defaults for all supported types.
cc: @sttts
> :sparkles: Add a marker to support field defaulting in crd schema

- cmd/controller-gen/main.go
- cmd/type-scaffold/main.go
- pkg/version/version.go
It's useful to know the version of a `controller-gen` binary lying around. We could write checks in the kubebuilder `Makefile` to upgrade `controller-gen` when needed, or at least warn about it.
Fixes: #259 
I checked that this indeed worked with main modules when using `go get`: https://github.com/dlespiau/go-main-module-version.
> :sparkles: Add a --version option to controller-gen

- cmd/helpgen/main.go
- pkg/crd/markers/zz_generated.markerhelp.go
- pkg/crd/zz_generated.markerhelp.go
- pkg/genall/zz_generated.markerhelp.go
- pkg/webhook/zz_generated.markerhelp.go
Trim leading space from generated marker help `Details` field
> :sparkles: Trim leading space from generated marker help `Details` field

- pkg/crd/known_types.go
Adds support for the apiextensions-apiserver JSON type.
Without this patch I get the following error:
```
/Users/james/go/src/github.com/jetstack/cert-manager/vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types_jsonschema.go:98:2: enountered struct field "Raw" without JSON tag in type "JSON"
```
/cc @DirectXMan12
> 🐛 Add apiextensions JSON type to known_types.go

- pkg/webhook/parser.go
According to https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/, mutating controllers are invoked before validating controllers, not after.
Fixes https://github.com/kubernetes-sigs/kubebuilder/issues/1075.
> 📖 Fix documentation for mutating webhooks.

- pkg/crd/gen.go
- pkg/version/version.go
Generated CRDs will be annotated with the version info of the controller-gen.
The annotation is `controller-gen.kubebuilder.io/version` and values will be `v0.2.2` is v0.2.2 version was used.
This annotation will help us with:
- Debugging CRD generation issues for ex. we can determine what version of controller-gen was used to generate a particular CRD
- Analyze generated CRDs in the field using Github queries to determine the distribution of controller-gen version. That can help in dropping deprecated features etc.
> :sparkles: add controller-gen attribution info to CRD

- pkg/genall/genall.go
- pkg/genall/options.go
- pkg/schemapatcher/gen_integration_test.go
Since we changed genall to use pointers to generators to make them
comparable, we'll need to actually keep track of the specific instance
of a given generator in the Runtime, otherwise things like output rules
don't get applied correctly.
> :bug: Use pointers to generators everywhere

- go.mod
- pkg/crd/markers/validation.go
- pkg/crd/markers/zz_generated.markerhelp.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
- pkg/crd/zz_generated.markerhelp.go
Marker syntax:
- `kubebuilder:pruning:PreserveUnknownFields`
- `kubebuilder:validation:EmbeddedResource`
Fixing https://github.com/kubernetes-sigs/controller-tools/issues/281
> Add x-kubernetes-{embedded-resource,preserve-unknown-fields} support

- pkg/crd/markers/crd.go
following the kubebuilder docs to setup 
`+kubebuilder:resource:scope=cluster` marker to generate manifests will have following error messages when install the generated CRD object 
```
The CustomResourceDefinition "stagerolebindings.cloudnative.example.com" is invalid: spec.scope: Unsupported value: "cluster": supported values: "Cluster", "Namespaced"
```
Current marker document CRD generation https://kubebuilder.io/reference/markers/crd.html use lower cased "namespaced" or "cluster" for CRD scope, which should be upper case in first letter according to https://godoc.org/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions#ResourceScope
> :book: CRD scope

- pkg/crd/gen.go
To avoid a breaking change in crd-gen, we need to default to
`preserveUnknownFields: true` if you're just generating v1beta1 CRDs.
In all other cases (multiple versions, v1 only), we default to
`preserveUnknownFields: false`, as this is the reccomended default and
required by v1.
We also introduce an option to crd-gen to allow overriding this
(`crd:preserveUnknownFields`).
> :bug: preserveUnknownFields: true on v1beta1, option

- pkg/crd/testdata/README.md
- pkg/deepcopy/testdata/README.md
The url “https://book.kubebuilder.io/cronjob-tutorial.html” has been changed to  “https://book.kubebuilder.io/cronjob-tutorial/cronjob-tutorial.html”
> :book: update URL in README.md

- pkg/loader/loader.go
This fixed an issue where `controller-gen` panics when encountering an import loop. This is especially problematic because when running `make` as part of the default Kubebuilder build `controller-gen` runs before the compiler, thus an import loop can be hard to detect.
> :bug: controller-gen panics when encountering an import loop

- go.mod
- go.sum
Minor improvements to pluralization rules including inching ever closer to correctly pluralizing 'Prometheus'
> ✨  update flect library to v0.2.0

- pkg/crd/markers/zz_generated.markerhelp.go
- pkg/crd/zz_generated.markerhelp.go
This PR adds the updated, autogenerated helper functions for Scope and PreserveUnknownFields, which were changed by https://github.com/kubernetes-sigs/controller-tools/commit/64c9bf947355b254ee360805608f68d6b0cf4028 (https://github.com/kubernetes-sigs/controller-tools/pull/355) and https://github.com/kubernetes-sigs/controller-tools/commit/6eb7baf89e3f2d8dc6c650a06089bb8fefcc447c (https://github.com/kubernetes-sigs/controller-tools/pull/362) respectively.
> Update helper functions for Scope, PreserveUnknownFields

- pkg/crd/known_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
This PR address the issue #328 
We need this because we want to use the `controller-gen` tool to start managing our CRDs. But the generated CRD only allows `string` types for `Quantity`.
> ✨ Change Quantity type to int-or-string

- pkg/webhook/parser.go
Even if there are no webhooks an empty webhook/manifests.yaml file is created.
The PR first checks if there are webhooks and only then calls WriteYAML.
>  ✨ Do not create empty webhook/manifests.yaml file

- OWNERS
- OWNERS_ALIASES
This cleans up the OWNERS file, making sure only active project members
are listed and the links are in line with the latest docs.
> :running: Clean up OWNERS file

- pkg/webhook/parser.go
Extends the marker documentation for webhook generation for `name` and `path`.
The OpenAPI specs for webhooks require the name is a domain name.
The path is handled specially by controller-runtime, so this adds documentation on how controller-runtime handles it here:
https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/builder/webhook.go#L158
Otherwise the webhook configuration generated by controller-tools will not match what actually runs with controller-runtime
> Extend webhook marker documentation

- pkg/crd/gen.go
- pkg/schemapatcher/gen.go
It makes more sense to return a hash set instead of a list, since hash set help de-duplicate group-kind.
> :bug: use map in FindKubeKinds

- pkg/crd/markers/crd.go
- pkg/crd/spec.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Singular argument on `+kubebuilder:resource` marker was never actually applied to CRD. This PR fixes it.
Fixes https://github.com/kubernetes-sigs/controller-tools/issues/343
Also fixes a small typo 🙃
> 🐛Fix singular argument for resource marker

- pkg/crd/flatten.go
The fix was untested, and not in the correct place.
Reverts kubernetes-sigs/controller-tools#412
> Revert "Resolve reference in order to remove $ref which is not supported by k8s"

- pkg/webhook/parser.go
- pkg/webhook/zz_generated.markerhelp.go
Signed-off-by: Vince Prignano <vincepri@vmware.com>
Sidenote: we need to add verification to the CI jobs
> :running: Make webhook marker MatchPolicy optional

- pkg/crd/markers/crd.go
- pkg/crd/markers/zz_generated.markerhelp.go
- pkg/crd/spec.go
Used to set `served=false` for an apiversion.
> ✨ Add kubebuilder:unservedversion CRD marker

- pkg/webhook/parser.go
This handles the case where the matchpolicy is not set using a webhook
marker.
Fixes #417
> 🐛 do not error when webhook matchpolicy unset

- pkg/crd/schema.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
- pkg/webhook/zz_generated.markerhelp.go
for the time being `controller-gen` does not accept pointers as map values and IMHO my patch should fix this problem as shown below.
```
$ tree .
.
├── api.go
├── go.mod
└── go.sum
0 directories, 3 files
```
```
$ cat api.go
package crd
import (
metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)
// +kubebuilder:object:root=true
// +kubebuilder:object:generate=true
// +groupName=example.org
type Env struct {
A int    `json:"a"`
B string `json:"b"`
}
type App struct {
metav1.TypeMeta   `json:",inline"`
metav1.ObjectMeta `json:"metadata,omitempty"`
Envs map[string]*Env `json:"envs,omitempty"`
}
```
using the latest controller-gen(https://github.com/kubernetes-sigs/controller-tools/commit/9d85d107df07a210d8b23d2b612365fd66bbe187)
```
$ /tmp/controller-gen-9d85d107d crd paths=./... …
```
> :sparkles: add support for pointers as map values

- pkg/crd/spec.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
This sets the CRDs status to empty so it is no longer generated in CRD yamls.
This was originally added in https://github.com/kubernetes-sigs/controller-tools/pull/203 which confuses me because v1beta1 has had the optional marker for awhile https://github.com/kubernetes/kubernetes/pull/66102/files#diff-3029a18192feb70af52de676209da9b6R206
This is currently a problem because continuous delivery tools cant converge when applying them against the updated server set properties
> :sparkles: Remove status from generated CRDs

- pkg/crd/schema.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Currently controller-gen complains about structs with missing json tags even
when those structs implement custom JSON marshalling.
With this change we check if a type implements custom JSON marshalling and if it
does, we output schema for Any type. This still allows the validation type to
overriden with a marker.
Fixes #391
> ✨ Generate schema for types with custom JSON marshaling as Any type

- pkg/crd/flatten_type_test.go
- pkg/crd/schema_visitor.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Without this change running controller-gen on Knative's APIs
results in unexpanded reference for the Conditions[1] type in
the generated OpenAPI schema:
conditions:
$ref: '#/definitions/knative.dev~1pkg~1apis~0Conditions'
After this change Conditions gets properly flattened and no references
are present in the resulting schema.
Fixes #324
[1] https://github.com/knative/pkg/blob/ce05a3de31ed80e98862a0ea024977097fd0e4a5/apis/duck/v1/status_types.go#L34
> 🐛 Fix flattening chains of references to references

- pkg/crd/gen.go
- pkg/crd/parser.go
- pkg/crd/schema.go
- pkg/crd/zz_generated.markerhelp.go
This can be used to enable `float32`/`float64` (go type) -> `number` (json schema) for CRDs. It is off by default because floats are not recommended in CRDs.
Discussion about this originated in #245 (which is now closed). @DirectXMan12 had suggested using a flag by this name to allow conditional supporting of floats. There's also at least one other issue asking about this (indirectly) at #93.
> ✨ Add support for AllowDangerousTypes crd flag (enables float support)

- pkg/crd/gen.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/zz_generated.markerhelp.go
v1beta1 CRDs are deprecated in k8s v1.19 in favor of v1. To prepare for a release with deps upgraded to this k8s version, the default generated CRD version should be v1.
/cc @DirectXMan12 @vincepri @joelanford
> :warning: pkg/crd: default CRD version to v1

- pkg/crd/spec.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Reverts kubernetes-sigs/controller-tools#433
In kubernetes-sigs/controller-tools#433 I attempted to drop the entire status block from generated CRDs for tools like ArgoCD. I wrongly assumed that the `omitempty` marker on the CRD status field made it so the status field would not be generated at all. This is not true due to it not being a pointer, causing it always to be generated. We will need to manually set these still to pass validation
> :sparkles: Revert ":sparkles: Remove status from generated CRDs"

- pkg/webhook/conv.go
- pkg/webhook/parser.go
- pkg/webhook/parser_integration_test.go
- pkg/webhook/testdata/manifests.v1beta1.yaml
- pkg/webhook/testdata/webhook.go
- pkg/webhook/zz_generated.markerhelp.go
This PR implements support to generate {Mutating, Validating}WebhookConfiguration with version `v1`.
Fixes #419
The first intention was to add a package marker `webhookVersions=<[]string>` for the user to specify the versions that want to generate. It will default to `v1` if the `webhookVersions` is not specified. However, after discussion with @estroz (https://github.com/kubernetes-sigs/controller-tools/pull/469#discussion_r469346611), we found out this cannot work nicely because, for different versions of WebhookConfiguraiton, Some fields (SideEffects, AdmissionReviewVersions) can have different available values, and if one value in that marker is invalid for one version then you can't generate the config for either version.
So we decided to use an optional field marker …
> ⚠ Add admissionregisteration/v1 support for webhook

- pkg/webhook/parser.go
- pkg/webhook/testdata/manifests.v1beta1.yaml
- pkg/webhook/testdata/webhook.go
- pkg/webhook/zz_generated.markerhelp.go
This PR is a follow-up of #469 
This PR adds support to config `AdmissionReviewVersions` for webhook, and this is required for generating v1 webhook.
Instead of defaulting it for the user, now if it is not specified, we return an error, so this is a breaking change.
> ⚠ Add AdmissionReviewVersions support for webhook

- pkg/crd/gen.go
It is not valid to specify `default` field values in v1beta1 CRDs.
This pull request strips the generated openapi schema of all instances of `default` being specified.
My only issue with this implementation is that it is non-obvious to users that this has happened, which could cause unexpected behaviour.
Fixes #445 
related #480
> ✨ Remove 'default' fields from v1beta1 CRDs

- pkg/crd/known_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Mitigation to help resolve #444 whilst waiting for https://github.com/kubernetes/enhancements/pull/1928 to merge.
This patch will cause resources that embed e.g. `ServiceSpec` or `PodSpec` to have the `default` field set for the `protocol` field:
```yaml
ports:
items:
properties:
appProtocol:
type: string
name:
type: string
nodePort:
format: int32
type: integer
port:
format: int32
type: integer
protocol:
default: TCP
type: string
targetPort:
anyOf:
- type: integer
- type: string
x-kubernetes-int-or-string: true
required:
- port
type: object
type: array
x-kubernetes-list-map-keys:
- port
- protocol
x-kubernetes-list-type: map
```
This will workaround the issue described in #444, and can be easily extended to new fields/types as they are discovered.
We should probably also consider fixing …
> ✨ Set default value for corev1.Protocol type if not already specified

- pkg/crd/markers/validation.go
- pkg/markers/parse.go
- pkg/markers/parse_test.go
Signed-off-by: knight42 <anonymousknight96@gmail.com>
This adds support for negative integers in the marker syntax parser.  This is useful for markers like `+kubebuilder:validation:Minimum`
> ✨ feat: parse negative integers

- pkg/crd/markers/validation.go
- pkg/crd/markers/zz_generated.markerhelp.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
This PR adds `minProperties`/`maxProperties` validation markers.
fixes #487
> ✨ add min/max properties validation

- .github/workflows/verify.yml
This will allow us to follow a similar process for release notes as
controller-runtime -- it verifies that title has emoji on it, and then does some basic descriptiveness checks for the PR description.
More info can be found at https://github.com/kubernetes-sigs/kubebuilder-release-tools.
> :seedling: Add PR title/description checking

- README.md
- VERSIONING.md
This adds versioning/releasing guidelines that reference the common
guidelines in kubebuilder-release-tools, with a few
controller-tools-specific reminders.
> :book: Add versioning guidelines

- pkg/crd/schema.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
This reverts commit e0d7c9d9723baea95e57a12751864e2e8f7d7c0f.
`Any` is not a valid (tested with both v1.18 and v1.19):
```
* spec.validation.openAPIV3Schema.properties[spec].properties[pipeline_run_spec].properties[pipelineSpec].properties[params].items.properties[default].type: Unsupported value: "Any": supported values: "array", "boolean", "integer", "number", "object", "string"
```
See also https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#type although that list doesn't match whats in the error
cc @skaslev 
Fixes https://github.com/kubernetes-sigs/controller-tools/issues/502
/assign @vincepri
> :bug: Don't generate schema with `Any` in it, its not supported

- pkg/crd/markers/zz_generated.markerhelp.go
- pkg/webhook/parser.go
- pkg/webhook/testdata/manifests.v1beta1.yaml
- pkg/webhook/testdata/manifests.yaml
- As per the comment in source, this field is no longer needed.
> 🐛 Remove unneeded caBundle: Cg== value

- pkg/crd/markers/validation.go
- pkg/crd/markers/zz_generated.markerhelp.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
- pkg/rbac/zz_generated.markerhelp.go
Remove the duplicated kubebuilder:validation:XPreserveUnknownFields marker.
Fixes #380
> ✨Deprecate the duplicated kubebuilder:validation:XPreserveUnknownFields marker.

- pkg/crd/gen.go
- pkg/crd/gen_integration_test.go
- pkg/crd/testdata/gen/foo_crd_v1.yaml
- pkg/crd/testdata/gen/foo_crd_v1beta1.yaml
- pkg/crd/testdata/gen/foo_types.go
This is a small follow up to #481 to include test cases and a warning for when v1beta1 CRDs are stripped of defaults.
Also fixes a gosec lint issue caused by "Implicit memory aliasing in for loop"
> ✨ Add test and warning for v1beta1 default removal

- go.mod
- go.sum
- pkg/crd/parser_integration_test.go
- pkg/crd/spec.go
- pkg/crd/testdata/plural/plural.example.com_testquotas.yaml
- pkg/crd/testdata/plural/types.go
Changing `Kind` to lowercase first will cause the `Pluralize` function to misjudge word formation, and will generate wrong plurals for words with special endings, we take `TestQuota` as an example (ending with `ta`):
before:
```
TestQuota --ToLower--> testquota --will be Pluralized as testquota--> testquota
```
after:
```
TestQuota --will be Pluralized as Quota--> Testquotas --ToLower--> testquotas
```
/assign @DirectXMan12
> 🐛 Generate plural words for Kind correctly

- .golangci.yml
- pkg/crd/markers/validation.go
- pkg/crd/markers/zz_generated.markerhelp.go
- pkg/crd/schema.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
- test.sh
This marker will avoid trying to do any type detection on any struct field on which it is set. This gives users a safety valve when they hit an edge case where type inference does the wrong thing for them.
This fixes #291, which was recently re-broken by fixing #502
Signed-off-by: Max Smythe <smythe@google.com>
> :sparkles: Add crd:validation:Schemaless marker

- pkg/crd/gen.go
- pkg/crd/gen_integration_test.go
- pkg/crd/testdata/gen/bar.example.com_foos.v1beta1.yaml
- pkg/crd/testdata/gen/bar.example.com_foos.yaml
- pkg/crd/testdata/gen/foo_types.go
Ensures that generated CRDs do not have a description generated from godoc comments on the ObjectMeta of the corresponding go type.
Fixes #386 
CRD structural schema requires that if metadata is specified, then only restrictions on metadata.name and metadata.generateName are allowed.
metadata.description is not allowed
xref: kubernetes/kubernetes#86800
> 🐛 Don't generate description on metadata of CRD structural schema

- go.mod
- pkg/crd/gen.go
- pkg/crd/known_types.go
- pkg/crd/parser.go
- pkg/crd/parser_integration_test.go
- pkg/crd/zz_generated.markerhelp.go
This PR addresses issue comments from #539, notably linking to a comment by @sttts. The original description of #539 is copied below.
This is desired for an issue we are seeing in Rook with CRD gen: https://github.com/rook/rook/issues/7629
We wish to keep annotations in embedded object meta.
--------
This PR makes it so embedded `ObjectMeta` in the CRD get's properly generated if the generator option `generateEmbeddedObjectMeta=true` is passed, this is needed because if a CRD has embedded `ObjectMeta` in any field and `preserveUnknowFields` is set to false, all the metadata will be lost when doing conversion between versions.
An example on how to have the embedded ObjectMeta generated in the resulting CRD
```
controller-gen crd:maxDescLen=0,generateEmbeddedObjectMeta=true paths=. …
```
> ⚠ Generate Embedded ObjectMeta in the CRDs, plus addressed comments

- pkg/crd/markers/crd.go
- pkg/crd/markers/zz_generated.markerhelp.go
- pkg/crd/parser_integration_test.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/deprecated/types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
- pkg/crd/testdata/unserved/types.go
This PR introduces the marker `deprecated` which would mark a CRD version as deprecated in the generated output, it supports a deprecation warning message
Example  usage: 
```
// +kubebuilder:deprecated:warning="This version is deprecated in favor of other.crd.com/v2"
```
the result is that the version that has this marker would include the following fields
```
deprecated: true
deprecatedWarning: "This version is deprecated in favor of other.crd.com/v2"
```
> ✨ Add deprecated marker for versions

- cmd/helpgen/main.go
- pkg/crd/crd_spec_test.go
- pkg/crd/desc_visitor_test.go
- pkg/crd/flatten_all_of_test.go
- pkg/crd/flatten_type_test.go
- pkg/crd/known_types.go
- pkg/crd/markers/zz_generated.markerhelp.go
- pkg/crd/zz_generated.markerhelp.go
- pkg/deepcopy/zz_generated.markerhelp.go
- pkg/genall/zz_generated.markerhelp.go
- pkg/rbac/zz_generated.markerhelp.go
- pkg/schemapatcher/gen.go
- pkg/schemapatcher/zz_generated.markerhelp.go
- pkg/webhook/zz_generated.markerhelp.go
- test.sh
There's a bunch of files that have changes when `gofmt -s -w`-ed,
this fixes all of them.
Updated helpgen to produce these results, and enabled gofmt in our lints.
Signed-off-by: Zou Yu <zouy.fnst@cn.fujitsu.com>
> :seedling: Fix some gofmt warnings

- pkg/schemapatcher/gen.go
Quite similar to https://github.com/kubernetes-sigs/controller-tools/pull/557, this applies the very same options now available on the CRD generator to be available on the `schemapatch` command. Since this option only really affects the generation of the schema anyway, it seems like it should be available on both equally.
> ✨ Generate embedded ObjectMeta with schemapatch as well

- pkg/loader/loader.go
Fixes #459
As pointed out by WG Naming in the respective issue.
> 🌱 Drop usage of dummy

- pkg/crd/markers/validation.go
As of today, if you want to add a pattern to a CRD field, the field has to be a string or you have to specify that it is of type string. Patterns are also compatible with `XIntOrString` but the CRD generator won't allow you to do this.
When patterns are used with the `IntOrString` type, the validation is run if a string is detected, but not run when an integer is detected. I have a use case where I want to ensure that the field is either an integer or percentage, and a pattern can be useful for validating the percentage.
There is also a workaround today where you can manually set a `IntOrString` field to a string type, but then validation blows up when you put an integer in.
This PR should allow patterns when an `IntOrString` field is used.
>  🐛  Allow pattern usage for IntOrString fields

- pkg/crd/markers/validation.go
- pkg/crd/markers/zz_generated.markerhelp.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
This is a follow up to fix #608 which I hadn't appropriately tested before proposing it 😞 
I tried this out this morning and worked out that it wasn't working, there are two reasons for this.
The condition check was wrong, we meant to check for the schema *not* being an IntOrString.
The second issue is that the additional information for the type that the generator applies (eg setting XIntOrString=true) is not done until way later in the generation than the markers being applied. Looking at the existing code, the "fix" for this seems to be that you have to apply an additional marker, eg the Type marker, that sets the required fields early.
So this introduces a new marker `// +kubebuilder:validation:XIntOrString` which marks the type as an IntOrString early to allow the pattern marker to …
> 🐛 Fix int or string pattern application

- pkg/crd/schema.go
Currently, we fall through and just emit an error telling that floats
are not supported which lead to ppl creating prs to add support. We
actually do support them although that is discouraged. This change makes
us emit a more helpful error.
Closes https://github.com/kubernetes-sigs/controller-tools/pull/566
Closes https://github.com/kubernetes-sigs/controller-tools/issues/245
> :bug: Be more helpful with floats when allowDangerousTypes=false

- pkg/crd/schema.go
- pkg/crd/schema_test.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Lifts the restriction currently imposed on map value types (that if they are arrays they must be arrays of `string`s), per https://github.com/kubernetes-sigs/controller-tools/pull/518#issuecomment-920387673. We have encountered this while trying to use `controller-gen` (https://github.com/Azure/azure-service-operator/issues/1489).
Also add a way to add simple schema-transform tests, rather than by adding items to `cronjob_types.go` (where the output is validated by inspection).
> ✨ Allow maps of arrays of non-string types

- pkg/crd/testdata/plural/plural.example.com_testquotas.yaml
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
I am considering submitting a functional PR, and had a look in the codebase - to get a bit familiar. Since I am probably going to suggest a new CRD marker, I took special note on the [process for generating testdata](https://github.com/kubernetes-sigs/controller-tools/tree/master/pkg/crd/testdata#crd-integration-test-testdata).
And it seems like the "golden output file" hasn't been re-generated lately. At least I get a big diff related to newlines in the desciption fields. Possibly related issue: #514.
> :seedling: Regenerate CRD Integration Test testdata

- pkg/crd/markers/zz_generated.markerhelp.go
- pkg/schemapatcher/zz_generated.markerhelp.go
While [generating testdata](https://github.com/kubernetes-sigs/controller-tools/tree/master/pkg/crd/testdata#crd-integration-test-testdata), I noticed that the generated code appears outdated. So I did a full regenerate throughout the project.
And it seems like help is not generated for a new option recently added to `schemapatcher`. This PR fixes this.
> :bug: schemapatcher: help should include all options

- pkg/crd/testdata/gen/bar.example.com_foos.v1beta1.yaml
- pkg/crd/testdata/gen/bar.example.com_foos.yaml
- pkg/genall/genall.go
- pkg/webhook/parser_integration_test.go
- pkg/webhook/testdata/invalid-admissionReviewVersionsRequired/manifests.yaml
- pkg/webhook/testdata/invalid-sideEffects/manifests.yaml
- pkg/webhook/testdata/invalid-v1beta1NotSupported/manifests.yaml
- pkg/webhook/testdata/manifests.yaml
- pkg/webhook/testdata/valid/manifests.yaml
Currently generated YAML files all have  `\n---\n` prepended to them. Although that's not an issue when using `kubectl apply` with those files, it requires extra work when trying to do something simple like parse CRD yaml from a controller. Although not a significant issue, it's caused us ([Gateway API](https://gateway-api.sigs.k8s.io/) + associated controller authors) to have to workaround it in several places. When parsing YAML files like this, the leading new line is parsed as an empty yaml struct, so we need to write code that can handle this empty/invalid object that starts all our generated YAML CRDs.
It looks like this code originated from https://github.com/kubernetes-sigs/controller-tools/pull/208, and this particular part of the change does not seem like it was intentional. …
> 🐛 Updating WriteYAML to not add empty line to start files

- pkg/crd/gen.go
- pkg/crd/parser.go
- pkg/crd/parser_integration_test.go
- pkg/crd/schema.go
- pkg/crd/schema_test.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
- pkg/crd/zz_generated.markerhelp.go
Unexported fields currently cause CRD YAML generation to fail. Since these fields can't and don't have JSON tags, `structToSchema` adds errors due to the missing tags.
Example output when using structs generated from a protobuf:
(error text [originates here](https://github.com/kubernetes-sigs/controller-tools/blob/ffa54949a74756bbb4d5c41ae4fe8d6fea759ae7/pkg/crd/schema.go#L338))
```
encountered struct field "state" without JSON tag in type "Storage"
encountered struct field "sizeCache" without JSON tag in type "Storage"
encountered struct field "unknownFields" without JSON tag in type "Storage"
```
This adds tests for @shawn-hurley's original work in https://github.com/kubernetes-sigs/controller-tools/pull/524.
I've also added a generator flag so this isn't enabled by default, as this is …
> :bug: Skip unexported fields when generating CRDs

- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
This invocation now requires ignoreUnexportedFields=true. Regenerating
it produces a field-ordering- and whitespace-only manifest diff, but
the integration tests are only concerned with significant differences.
> :seedling: Update cronjob_types.go go:generate invocation and re-generate.

- pkg/crd/gen.go
- pkg/crd/spec.go
- pkg/crd/testdata/gen/bar.example.com_foos.v1beta1.yaml
- pkg/crd/testdata/gen/bar.example.com_foos.yaml
- pkg/crd/testdata/plural/plural.example.com_testquotas.yaml
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
- pkg/genall/genall.go
- pkg/rbac/parser.go
- pkg/webhook/parser.go
It's tricky to get the existing CRD types to not include the status,
so we instead allow for filtering of the map just before writing.
Issue #456
> :bug: CRD generation: remove status before writing

- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
- pkg/loader/refs.go
This fixes #613 
Signed-off-by: Joe Kralicky <joe.kralicky@suse.com>
> 🐛 Fixed panic when parsing selector expressions containing composite literals

- go.mod
- go.sum
This PR bumps [flect](https://github.com/gobuffalo/flect) dependency -- used for [Pluralize](https://github.com/kubernetes-sigs/controller-tools/blob/ea8d4ead3e34dac7bb792cedc6d3cd7decf63137/pkg/typescaffold/resource.go#L45) logic -- to the latest version, [`v0.2.5`](https://github.com/gobuffalo/flect/releases/tag/v0.2.5). 
I am having issues generating a controller for a resource, `Fleet`, because Flect does not pluralize it correctly. The latest release includes a [fix to correctly pluralize `Fleet`](https://github.com/gobuffalo/flect/pull/54) (and similar words).
> 🏃 Update to Flect v0.2.5

- test.sh
`install.goreleaser.com` is now deprecated and stopped working so the tests
in new PRs are failing. Instructions are from https://golangci-lint.run/usage/install/#other-ci.
> :bug: ci: fix golangci-lint installation

- pkg/crd/gen.go
- pkg/crd/gen_integration_test.go
- pkg/crd/testdata/gen/zoo/bar.example.com_zooes.v1beta1.yaml
- pkg/crd/testdata/gen/zoo/bar.example.com_zooes.yaml
- pkg/crd/testdata/gen/zoo/zoo_types.go
- pkg/schemapatcher/gen.go
Fixes #675 by sorting `kubeKinds` in `FindKubeKinds`
> ✨ crd/gen: sort FindKubeKinds

- pkg/crd/flatten.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
This PR allows setting `PreserveUnknownFields` at both type and field level.
Fixes #688
> :bug: Allow setting PreserveUnknownFields at both type and field level

- pkg/crd/flatten.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
This is an manual cherry-pick of https://github.com/kubernetes-sigs/controller-tools/pull/697
> 🐛 Fix crd flattening for structType marker to not create duplicate entries for XMapType

- pkg/webhook/parser.go
- pkg/webhook/testdata/manifests.yaml
- pkg/webhook/testdata/valid/manifests.yaml
- pkg/webhook/testdata/valid/webhook.go
- pkg/webhook/testdata/webhook.go
- pkg/webhook/zz_generated.markerhelp.go
Mutating webhooks using controller-gen markers for generating
MutatingWebhookConfigration cannot control reinvocationPolicy.
This field must always be added manually afterwards should the
webhook need to set its value.
Add support for reinvocationPolicy marker for Mutating Webhooks.
Fixes: #641
> :sparkles: pkg/webhook: add support for reinvocationPolicy marker

- test.sh
test.sh triggers a warning:
WARN [runner] The linter 'golint' is deprecated (since v1.41.0) due to: The
repository of the linter has been archived by the owner.  Replaced by revive.
Change the script accordingly.
> :running: golangci-lint: use revive instead of golint linter

- pkg/genall/options.go
- pkg/genall/zz_generated.markerhelp.go
Add paths description on how to specify multiple paths.
<TODO: Would be nice add here the problem faced and from where you got the info to update this one>
> 📖 Update controller-gen CLI documentation for better info regards paths argument  

- pkg/schemapatcher/gen.go
- pkg/schemapatcher/testdata/valid/example.cr.yaml
- pkg/schemapatcher/testdata/valid/random.yaml
While trying to add some example and additional YAML files to my API directory, eg schemas for other tools unrelated to controller-gen, I noticed that the generator would error out because there were files it didn't think were CRDs
```
load "example/v1/stable.testsuite.yaml": apiVersion "" not supported
Error: not all generators ran successfully
```
This patch moves the check for the Kind ahead of the check for the supported group version, this means that even if we find a type meta whose Kind is empty or not a CustomResourceDefintion, that we just ignore the file. Likewise if the API version is empty, we can ignore it, it's probably not a valid kube like file.
> 🐛 Ensure schemapatcher does not error when non CRD yaml files are present

- pkg/genall/output.go
When using +output:dir=./something and attempting to write a nested path, the current implementation does not work.
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
> :bug: output: ensure the directory exists

- test.sh
```
running golangci-lint
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
```
Fixes linter warnings. Replaced the deprecated linters with unused.
/assign @camilamacedo86
>  🐛 Update CI golangci-lint checks to avoid deprecated linters

- pkg/loader/loader.go
When having sub-packages, and one of them is out of sync, we might get an error such as:
```
err: exit status 1: stderr: go: updates to go.mod needed; to update it:
go mod tidy
```
Although this error is true, it was a nightmare to debug it and figure out that it was related to a sub-package.
This PR introduces a bit more verbosy error message that can help you to debug the issue:
```
Error: error in /Users/AlmogBaku/projects/myproject/subpackage: err: exit status 1: stderr: go: updates to go.mod needed; to update it:
go mod tidy
```
> :bug: return a bit more verbosy error messages for go-package errors

- pkg/crd/markers/crd.go
- pkg/crd/markers/zz_generated.markerhelp.go
- pkg/crd/parser_integration_test.go
- pkg/crd/spec.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Support api-approved annotation for CRD with k8s group
fixes #656
> ✨ Support api-approved annotation for CRD with k8s group

- .github/dependabot.yml
From a request on controller-runtime slack, there was an ask to add dependabot to both controller-runtime (https://github.com/kubernetes-sigs/controller-runtime/pull/2050) and controller-tools.
> 🌱 : dependabot addition

- pkg/crd/markers/topology.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
It has to have x-kubernetes-map-type: atomic set.
Fixes https://github.com/kubernetes-sigs/controller-tools/issues/752
> :bug: Fix the generation of listType=set

- pkg/crd/markers/topology.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Reverts kubernetes-sigs/controller-tools#753
Which could have side-effects with existing CRDs and should be reverted, upstream fix is incoming for the same issue
> :bug:  Revert Fix the generation of listType=set

- pkg/crd/gen.go
- pkg/genall/genall.go
- pkg/rbac/parser.go
- pkg/webhook/parser.go
This patch adds headerFile and year options to CRD, RBAC and Webhook generator
Currently headerFile and year options are available on only generate option.
This patch adds the option for YAMLs.
e.g. generate the crd with headerfile
```
go run sigs.k8s.io/controller-tools/cmd/controller-gen \
crd:crdVersions=v1,year=2021,headerFile="${PATH_TO_YOUR_BOILDER_PLATE}" \
output:crd:artifacts:config=config/crd/bases \
paths=./...
```
Fix https://github.com/kubernetes-sigs/controller-tools/issues/464
> ✨ Add header and year options for yaml generator

- pkg/crd/markers/crd.go
- pkg/crd/parser_integration_test.go
- pkg/crd/testdata/wrong_annotation_format/cronjob_types.go
When using 
```
+kubebuilder:metadata:annotations="api-approved.kubernetes.io=xxx"
``` 
#691 in CRD struct files to generate api-approved annotation, if the annotation is not in `metadata:annotations:"xxx=xxx"` format, eg: 
```
+kubebuilder:metadata:annotations="api-approved.kubernetes.io: xxx"
```
it triggers index out of range panic.
> :bug: fix index out of range panic when annotation is not in 'key=value' format

- pkg/crd/markers/validation.go
- pkg/crd/markers/zz_generated.markerhelp.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/gen/bar.example.com_foos.yaml
- pkg/crd/testdata/gen/foo_types.go
- pkg/crd/testdata/gen/zoo/bar.example.com_zooes.yaml
- pkg/crd/testdata/gen/zoo/zoo_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
- pkg/crd/zz_generated.markerhelp.go
- pkg/rbac/zz_generated.markerhelp.go
- pkg/webhook/zz_generated.markerhelp.go
> ✨ Add support for example marker

- pkg/crd/markers/validation.go
- pkg/crd/markers/zz_generated.markerhelp.go
fix typo `minimun` -> `minimum` that appears in the kubebuilder book marker validation page
> :book: fix typo: minimun -> minimum

- pkg/webhook/parser.go
- pkg/webhook/parser_integration_test.go
- pkg/webhook/testdata/valid-ordered/cronjob_types.go
- pkg/webhook/testdata/valid-ordered/manifests.yaml
- pkg/webhook/testdata/valid-ordered/webhook.go
This PR modified to generate webhook manifests sorted by name and added tests.
Now we get differently ordered manifests every time.
It isn't easy to compare generated manifests.
Please see https://github.com/kubernetes-sigs/controller-tools/issues/730 for more information.
> 🐛 Generate deterministic ordering for webhook manifests

- pkg/crd/gen.go
- pkg/crd/testdata/gen/bar.example.com_foos.v1beta1.yaml
- pkg/crd/testdata/gen/bar.example.com_foos.yaml
- pkg/crd/testdata/gen/zoo/bar.example.com_zooes.v1beta1.yaml
- pkg/crd/testdata/gen/zoo/bar.example.com_zooes.yaml
- pkg/crd/testdata/plural/plural.example.com_testquotas.yaml
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
- pkg/crd/testdata/testdata.kubebuilder.io_jobs.yaml
- pkg/genall/genall.go
- pkg/rbac/parser.go
- pkg/rbac/testdata/role.yaml
- pkg/webhook/parser.go
- pkg/webhook/testdata/invalid-admissionReviewVersionsRequired/manifests.yaml
- pkg/webhook/testdata/invalid-sideEffects/manifests.yaml
- pkg/webhook/testdata/invalid-v1beta1NotSupported/manifests.yaml
- pkg/webhook/testdata/manifests.yaml
- pkg/webhook/testdata/valid-ordered/manifests.yaml
- pkg/webhook/testdata/valid/manifests.yaml
Closes #402 
This issue has been open for awhile, but seemingly not _that_ big of a deal until kustomize v5 was released with a bug that converts `null` to `"null"`. And _that_ causes manifests to fail to apply.
https://github.com/kubernetes-sigs/kustomize/issues/5031
We can stem the tide in controller-tools by removing `creationTimestamp: null` just before writing the generated manifests. This was always unsightly/superfluous anyways.
> 🐛 remove metadata.creationTimestamp when generating CRDs, RBAC, and webhooks

- pkg/crd/gen.go
- pkg/crd/testdata/gen/bar.example.com_foos.v1beta1.yaml
- pkg/crd/testdata/gen/bar.example.com_foos.yaml
- pkg/crd/testdata/gen/zoo/bar.example.com_zooes.v1beta1.yaml
- pkg/crd/testdata/gen/zoo/bar.example.com_zooes.yaml
- pkg/crd/testdata/plural/plural.example.com_testquotas.yaml
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
- pkg/crd/testdata/testdata.kubebuilder.io_jobs.yaml
- pkg/genall/genall.go
- pkg/rbac/parser.go
- pkg/rbac/testdata/role.yaml
- pkg/webhook/parser.go
- pkg/webhook/testdata/invalid-admissionReviewVersionsRequired/manifests.yaml
- pkg/webhook/testdata/invalid-sideEffects/manifests.yaml
- pkg/webhook/testdata/invalid-v1beta1NotSupported/manifests.yaml
- pkg/webhook/testdata/manifests.yaml
- pkg/webhook/testdata/valid/manifests.yaml
Manual cherry-pick of #800 to backport to `release-0.11`
> 🐛 release-0.11: remove metadata.creationTimestamp when generating CRDs, RBAC, and webhooks

- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
This adds a field to the cronjob test data, that ensures that fields
which are marked twice (once through a type marker, one through a field
marker) still generate the correct yaml structure.
Signed-off-by: Jan Fajerski <jfajersk@redhat.com>
> :sparkles: testdata/cronjob_types.go: add NestedStructWithSeveralFieldsDoubleMarked

- go.mod
- pkg/crd/gen_integration_test.go
- pkg/crd/markers/crd.go
- pkg/deepcopy/traverse.go
- pkg/genall/output.go
- pkg/markers/parse.go
- pkg/typescaffold/scaffold.go
- test.sh
- Upgrade to `go` 1.20
- Upgrade `golangci-lint` to v1.52.2
- Fix lint findings
> :sparkles:Upgrade to go 1.20

- pkg/markers/parse.go
- pkg/markers/parse_test.go
Markers that have number-like parts (like `0B7LDeoZta`) trigger parsing errors.
This causes `controller-gen` to fail (see https://github.com/cert-manager/cert-manager/issues/5955).
This PR updates the scanner, so it does not try to parse a string as numbers when we know it is a string instead of a number.
> 🐛 Fix marker parsing

- pkg/webhook/parser.go
- pkg/webhook/parser_integration_test.go
- pkg/webhook/testdata/invalid-admissionReviewVersionsRequired/manifests.yaml
- pkg/webhook/testdata/invalid-sideEffects/manifests.yaml
- pkg/webhook/testdata/invalid-sideEffects/webhook.go
- pkg/webhook/testdata/invalid-timeoutSeconds/cronjob_types.go
- pkg/webhook/testdata/invalid-timeoutSeconds/manifests.yaml
- pkg/webhook/testdata/invalid-timeoutSeconds/webhook.go
- pkg/webhook/testdata/invalid-v1beta1NotSupported/manifests.yaml
- pkg/webhook/testdata/invalid-v1beta1NotSupported/webhook.go
- pkg/webhook/testdata/manifests.yaml
- pkg/webhook/testdata/valid/webhook.go
- pkg/webhook/testdata/webhook.go
- pkg/webhook/zz_generated.markerhelp.go
I needed to change `timeoutSeconds` default value in a project created using `kubebuilder` and I realized that it is not possible to do that. So, I opened this PR.
> ✨ Adds new option `timeoutSeconds` to inform the the timeout for webhook resources

- pkg/genall/options.go
Return an error from controller-gen if the command includes multiple instances of the same generator. For example:
```
$ controller-gen "+crd:generateEmbeddedObjectMeta=true" rbac:roleName=manager-role crd webhook paths="~/src/operator/apis" +output:crd:artifacts:config=/tmp/wat
Error: multiple instances of 'crd' generator specified
```
I hit the issue described in https://github.com/kubernetes-sigs/controller-tools/issues/671 and was quite confused by it.
I'm not sure if you should ever be able to specify multiple of the same generator in a single run, as this causes apparently unintended effects. In my case, only honoring the `output` directive for one and dumping the other in the default location, with no obvious way to apply the `output` configuration to both.
I'm also unsure if …
> ✨ Return an error for duplicate generators

- pkg/crd/parser_integration_test.go
- pkg/crd/testdata/multiple_versions/common.go
- pkg/crd/testdata/multiple_versions/testdata.kubebuilder.io_versionedresources.yaml
- pkg/crd/testdata/multiple_versions/v1beta1/types.go
- pkg/crd/testdata/multiple_versions/v1beta2/types.go
- pkg/markers/collect.go
Fix #783.
As I described in https://github.com/kubernetes-sigs/controller-tools/issues/783#issuecomment-1487356924 , this issue is caused by using `Package.ID` as a key for cache of markers. This PR adds a testcase to reproduce the issue and fixes it by using `Package` itself instead.
> :bug: Change the type of `markers.Collector.byPackage`'s key from `string` to `*loader.Package`

- pkg/deepcopy/testdata/cronjob_types.go
- pkg/deepcopy/testdata/zz_generated.deepcopy.go
- pkg/deepcopy/traverse.go
Fix #809 
The PR fixes the implicit memory aliasing issue in autogenerated DeepCopy method when the field is a nested map.
> 🐛 Fix implicit aliasing issue in nested maps

- pkg/crd/markers/validation.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
- pkg/markers/parse.go
- pkg/markers/parse_test.go
Fixes: #550 
This PR adds support for `kubebuilder:default={}` type of annotations in controller tools.
> :bug: Add support for empty maps or lists

- pkg/crd/testdata/gen/bar.example.com_foos.yaml
- pkg/crd/testdata/gen/zoo/bar.example.com_zoos.yaml
- pkg/crd/testdata/gen/zoo/zoo_types.go
- pkg/crd/testdata/multiple_versions/common.go
- pkg/crd/testdata/multiple_versions/testdata.kubebuilder.io_versionedresources.yaml
- pkg/crd/testdata/plural/plural.example.com_testquotas.yaml
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
- pkg/crd/testdata/testdata.kubebuilder.io_jobs.yaml
- pkg/markers/collect_test.go
- pkg/markers/markers_suite_test.go
- pkg/markers/zip.go
- pkg/schemapatcher/gen_integration_test.go
- pkg/schemapatcher/testdata/expected/kubebuilder-example-crd.v1.yaml
- pkg/schemapatcher/testdata/expected/kubebuilder-unchanged-crd.yaml
Sometimes at type has examples about how to use it embedding something like a yaml on it, yamls should not be truncated and they are white space sensitive. This change keep the new lines and also remove the white space trimming only on /* comments.
Golang struct example with problematic comment.
```golang
// DnsState  DNS resolver state. Example partial yaml output of [NetworkState] with
// static DNS config:                                                           
// ```yaml                                                                      
// ---                                                                          
// dns-resolver:                                                                
//                                                                              
// …
> 🐛 crd: Respect multiline comments at godocs 

- pkg/crd/markers/doc.go
- pkg/crd/markers/priority.go
- pkg/crd/markers/topology.go
- pkg/crd/markers/validation.go
- pkg/crd/schema.go
- pkg/crd/schema_test.go
There's a need for more control over when SchemaMarkers are applied to a Schema. Right now there are two levels - 'First' and everything else. The iteration over the markers within this level is non-deterministic because we're iterating over a golang map type.
As an alternative we now collect all the markers and sort them based on a new priority. Markers can signal their priority by implementing the optional interface
```go
type ApplyPriority int64
type ApplyPriorityMarker interface {
ApplyPriority() ApplyPriority
}
```
This change is backwards compatible - downstream markers that implement `ApplyFirst()` will behave the same as before.
> :sparkles: Markers can now indicate their priority when applying

- pkg/crd/schema.go
- pkg/loader/loader.go
Fix deprecated following:
- `types.NewSignature` -> `types.NewSignatureType`
- `packages.LoadImports` -> `packages.NeedName | packages.NeedFiles | packages.NeedCompiledGoFiles | packages.NeedImports`
- `sets.String` -> `sets.Set[string]`
> ✨ Fix deprecated things

- pkg/crd/markers/register.go
- pkg/crd/markers/validation.go
- pkg/crd/schema.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
> :sparkles: pkg/crd: support validating internal list items on list types

- .github/dependabot.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/pr-dependabot.yaml
- .github/workflows/verify.yml
- .gitignore
- Makefile
- hack/go-install.sh
- pkg/crd/gen.go
- pkg/deepcopy/gen.go
- pkg/genall/options.go
- pkg/loader/loader.go
- pkg/markers/collect.go
- pkg/rbac/parser.go
- pkg/schemapatcher/gen.go
- pkg/typescaffold/resource.go
- pkg/version/version.go
- pkg/webhook/parser.go
- test.sh
More in line with controller-runtime
> :seedling: Update golangci-lint, Makefile, Actions

- .github/workflows/golangci-lint.yml
- .github/workflows/tools-releases.yml
> 🌱 Adjust branches for github actions

- pkg/crd/gen.go
- pkg/crd/gen_integration_test.go
Reinstate crd:preserveUnknownFields option removed by #607 to allow specifying the value of deprecated spec.preserveUnknownFields CRD field.
This is useful for updating CRDs that were automatically converted from v1beta1 version which had true as a default value and resulted in:
```
$ kubectl get crd foo.bar -o yaml | grep preserveUnknownFields
preserveUnknownFields: true
message: 'spec.preserveUnknownFields: Invalid value: true: must be false'
```
For #476
> :sparkles: crd: allow specifying spec.preserveUnknownFields

- pkg/crd/markers/validation.go
- pkg/crd/markers/zz_generated.markerhelp.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
- pkg/crd/zz_generated.markerhelp.go
- pkg/deepcopy/zz_generated.markerhelp.go
- pkg/genall/zz_generated.markerhelp.go
- pkg/rbac/zz_generated.markerhelp.go
- pkg/schemapatcher/zz_generated.markerhelp.go
- pkg/webhook/zz_generated.markerhelp.go
Add `messageExpression` support to `XValidation` marker.
Support was introduced in kubernetes via https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/2876-crd-validation-expression-language/README.md in k8s 1.25.
Fixes #858
> ✨ feat(crdvalidation): add messageExpression support to XValidation marker

- pkg/crd/markers/validation.go
- pkg/crd/markers/zz_generated.markerhelp.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
This allows you to specify the FieldPath and Reason on an XValidation rule. These can be useful when you are specifying validations that look at multiple fields or if the default reason of Invalid doesn't suit.
One use case would be a field that you no longer want set. You can add a CEL validation to make sure no one adds it to the object going forward. For this you would want the Forbidden reason, but the rule needs to be on the parent, which means you then need to use the field path to construct the correct error message path.
> ✨ Add FieldPath and Reason to XValidation marker

- pkg/crd/markers/validation.go
- pkg/crd/schema.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Fixes #943
Adds support for Kubernetes `+required` annotations on fields, fixes support for `+optional` annotations on fields, adds tests.
> :sparkles: add support for kubernetes +required annotations

- pkg/crd/markers/validation.go
- pkg/crd/markers/zz_generated.markerhelp.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
- pkg/markers/parse.go
This adds annotation support for `+default` markers for specifying default values in JSON format, as is done in core Kubernetes types and described in https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1929-built-in-default#summary
If both `+default` and `+kubebuilder:default` are specified, the kubebuilder-specific annotation wins.
Fixes https://github.com/kubernetes-sigs/controller-tools/issues/939
> ✨ Add support for +default markers

- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
- pkg/markers/collect_test.go
- pkg/markers/markers_suite_test.go
- pkg/markers/zip.go
This PR strips comments from the generated CRDs for clarity of the public API documentation.
The change aligns controller-tools with Kubernetes conventions for type descriptions:
- Line that only contains `---` separates the API description from comments. The leading lines are part of public documentation, the trailing lines are internal instructions such as code examples etc. As an example, see widely used type [`Condition`](https://github.com/kubernetes/apimachinery/blob/02a41040d88da08de6765573ae2b1a51f424e1ca/pkg/apis/meta/v1/types.go#L1508-L1522) that includes some example code that should not be considered as part of API documentation.
- Line that begins with TODO is internal note for implementer, and not part of public documentation of the type. See …
> :warning: Strip comments from CRD descriptions

- .github/dependabot.yml
After this PR dependabot:
* only creates at most one PR for go dependencies and one PR for GitHub actions
* only ignores k8s.io major & minor versions. Patch versions are bumped automatically
> 🏃 Optimize dependabot config

- pkg/crd/markers/package.go
- pkg/crd/markers/register.go
- pkg/crd/parser_integration_test.go
- pkg/crd/testdata/nogroup/types.go
- pkg/crd/testdata/testdata._cronjobs.yaml
Upstream introduced the use of empty groupName markers in kubernetes/kubernetes#125162. This breaks groupName parsing because its field is non-optional. Add an additional `mustOptional` function that takes anonymous field definitions and turns them into optional ones.
> :sparkles: Make the anonymous field of the groupName marker optional

- .github/workflows/golangci-lint.yml
- .github/workflows/pr-dependabot.yaml
- .github/workflows/release.yaml
- Makefile
This PR adds a GitHub action which will build & upload binaries whenever a tag/release is created
(this requires no changes to our release workflow, simply creating a GitHub release still works)
Example: https://github.com/sbueringer/controller-tools/releases/tag/v0.16.0-beta.0
Fixes #500
> ✨ Publish controller-gen binaries on release

- pkg/crd/flatten.go
- pkg/crd/flatten_all_of_test.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Fixes #997
This PR ensures XValidations are merged correctly when flattening the CRD schema.
> 🐛 Fix XValidations flattening

- .github/workflows/pr-gh-workflow-approve.yaml
This automatically approves GitHub actions once ok-to-test is set. This avoids that maintainers have to click the approve button for GitHub actions on PRs of new contributors
> 🌱 Add action to approve actions if ok-to-test is set

- README.md
> 📖 Document compatibility with k8s.io/*, client-go and Go

- pkg/rbac/parser.go
- pkg/rbac/testdata/controller.go
- pkg/rbac/testdata/role.yaml
Fixes the rbac generator for nonResourceURLs / when using `kubebuilder:rbac:urls` marker.
Kudos to @rakesh-garimella for reporting it at https://github.com/kubernetes-sigs/controller-tools/pull/937
This propably broke when implementing #937
@sbueringer : I think this is ok to cherry-pick?
> 🐛 rbac: fix adding nonResourceURLs including normalisation

- pkg/rbac/parser.go
- pkg/rbac/testdata/controller.go
- pkg/rbac/testdata/role.yaml
Fixes: #1036
Deduplication happened before renaming.
Now renaming before doing deduplication to fix this case for the core group.
> 🐛 rbac: fix deduplication of core group and add test coverage

- .github/workflows/release.yaml
- Makefile
- pkg/version/version.go
- pkg/version/version_suite_test.go
- pkg/version/version_test.go
Solves #1046 so that **`controller-gen`** binaries can show a proper version
---
Local testing:
```shell
% go build -ldflags "-X sigs.k8s.io/controller-tools/pkg/version.version=1.2.4" ./cmd/controller-gen
% ./controller-gen --version
Version: 1.2.4
```
> :bug: Allow CLI binaries to set a version

- pkg/webhook/parser.go
- pkg/webhook/parser_integration_test.go
- pkg/webhook/testdata/invalid-multiple-webhookconfigurations/cronjob_types.go
- pkg/webhook/testdata/invalid-multiple-webhookconfigurations/webhook.go
- pkg/webhook/testdata/valid-custom-name/cronjob_types.go
- pkg/webhook/testdata/valid-custom-name/manifests.yaml
- pkg/webhook/testdata/valid-custom-name/webhook.go
- pkg/webhook/zz_generated.markerhelp.go
```
❯ GOBIN=(pwd)/bin go install ./cmd/*
❯ ./bin/controller-gen webhook -w
Webhook
+kubebuilder:webhook:admissionReviewVersions=<[]string>,failurePolicy=<string>,groups=<[]string>[,matchPolicy=<string>],mutating=<bool>,name=<string>[,path=<string>][,reinvocationPolicy=<string>],resources=<[]string>[,sideEffects=<string>][,timeoutSeconds=<int>][,url=<string>],verbs=<[]string>,versions=<[]string>[,webhookVersions=<[]string>]  package  specifies how a webhook should be served.  
+kubebuilder:webhookconfiguration:mutating=<bool>[,name=<string>] …
```
> ✨ Allow customizing generated webhook configuration's name

- OWNERS_ALIASES
This PR adds @chrischdi (myself) to reviewers 🙂 🙃 .
This allows me to engage some more here and take responsibility when #1043 may get merged.
- [PR's I authored](https://github.com/kubernetes-sigs/controller-tools/pulls?q=sort%3Aupdated-desc+is%3Apr+author%3Achrischdi+is%3Aclosed)
- [PR's where I engaged in the past](https://github.com/kubernetes-sigs/controller-tools/pulls?page=1&q=is%3Apr+chrischdi+sort%3Aupdated-desc)
@sbueringer @vincepri @alvaroaleman
> 🌱 OWNERS: Promote chrischdi for being a reviewer

- pkg/crd/schema.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Fixes #1053 
In the latest version of go, a change was made to the generation of Alias types by default. From the release notes:
> By default, go/types now produces Alias type nodes for type aliases.
> This behavior can be controlled by the GODEBUG gotypesalias flag. Its
> default has changed from 0 in Go 1.22 to 1 in Go 1.23.
This provoked a panic in the localNamedToSchema function when processing any type alias becaused it was expecting only a *types.Named and not a *types.Alias. This can be fixed by using an anonymous interface to more broadly "ask" if the object supports the Obj() function instead of asking it to be a specific type. Types *types.Named and *types.Alias share this method so it can be used directly.
Note that it would be better (and would have made this easier to debug) …
> 🐛 pkg/crd: fix type casting panic with new default `*types.Alias` with Go 1.23

- pkg/crd/markers/crd.go
- pkg/crd/markers/zz_generated.markerhelp.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
- pkg/crd/zz_generated.markerhelp.go
- pkg/genall/zz_generated.markerhelp.go
Add support for selectable fields for custom resources https://github.com/kubernetes-sigs/controller-tools/issues/1039
>  :sparkles: Add selectablefield marker

- pkg/crd/schema.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Fixes #1076.
This is a follow up on 0a52475258f0 ("pkg/crd: fix type casting panic with new default *types.Alias"). Look for the commit message of the cited commit for more context.
/cc @markussiebert @sbueringer
> 🐛 pkg/crd: fix a missed type casting panic with new *types.Alias

- pkg/crd/schema.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Fixes #1071 
Without the type Alias being its own type (Go 1.22 see gotypesalias), in localNamedToSchema, the link is missing.
[ Upstream port of d944debcff34 ("Support type aliasing to basic types") ]
Previously, validation schema generation was skipped on a type alias:
type A = B
Whereas, a new type was fine:
type A B
This commit implements support for generating validation schemas for type aliases to basic types, i.e. string, int, etc.
> 🐛 pkg/crd: support validation on type alias to basic types

- pkg/rbac/parser.go
- pkg/rbac/testdata/controller.go
- pkg/rbac/testdata/role.yaml
> :bug: Handling Identical Kubebuilder Annotations in Different CRs with * Verbs

- pkg/crd/schema.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Whenever a type is encountered that implements `encoding.TextMarshaler` but not `encoding/json.Marshaler`, assume that it will be encoded as a string.
This is a breaking change, as types that implement `TextMarshaler` are now handled differently. On the other hand, this probably restores reality for all but the most customized setups, as Go's JSON package will also check for the presence of this interface, and output a JSON string.
> :warning: Add support for encoding.TextMarshaler

- pkg/crd/desc_visitor.go
- pkg/crd/desc_visitor_test.go
- pkg/crd/gen.go
- pkg/crd/gen_integration_test.go
- pkg/crd/testdata/gen/bar.example.com_foos_maxdesclen.yaml
Both of the items here are noted in a TODO in the code:
- Implement word boundary handling
- Add ellipsis after truncated text that doesn't end in a sentence terminator.
- (not in TODO) Skips processing if the description is already less than `MaxDescLen`
Outstanding questions about the initial implementation:
- Whether the ellipsis should be included in the `MaxDescLen`--in the implementation I've added it on to the end, so the total length could technically be more than `MaxDescLen` in some cases.
- Whether an ellipsis should be present after the sentence terminator (this implementation skips the ellipsis in this case).
> :sparkles: Handle word boundaries and add ellipsis for `MaxDescLen`

- hack/envtest/darwin/Dockerfile
- hack/envtest/linux/Dockerfile
- hack/envtest/windows/Dockerfile
> 🐛 Fix envtest build for v1.32.0

- envtest-releases.yaml
This PR promotes the envtest release for Kubernetes v1.32.0.
This time manually generated via https://github.com/kubernetes-sigs/controller-tools/pull/1113
> 🌱 Promotion of envtest release for Kubernetes v1.32.0

- pkg/crd/schema.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Fixes #1088.
This was actually breaking all struct type alias I think, not especially when using embedded/inline struct.
I tested that both should pass:
```shell-session
$ GODEBUG=gotypesalias=1 go test ./pkg/crd
ok      sigs.k8s.io/controller-tools/pkg/crd    2.888s
$ GODEBUG=gotypesalias=0 go test ./pkg/crd
ok      sigs.k8s.io/controller-tools/pkg/crd    2.928s
```
> :bug: pkg/crd: fix alias type parsing for struct type alias

- pkg/crd/markers/validation.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
This allows `maxLength` and `MinLength` on `x-kubernetes-int-or-string` fields. The former helps limit CEL validation costs.
> 🌱 Allow string validation on XIntOrString

- pkg/deepcopy/testdata/cronjob_types.go
- pkg/deepcopy/testdata/zz_generated.deepcopy.go
This seems like a copy-pasta from long ago. The name of the test/field is `NonPtr` but the type is `Ptr` like the test/field above it.
> 🌱 Test DeepCopy of contained non-pointer types

- pkg/deepcopy/testdata/cronjob_types.go
- pkg/deepcopy/traverse.go
Without this, Go type aliases cause a panic.
Fixes #813
> 🐛 Guard before type assertion

- .github/workflows/golangci-lint.yml
- .golangci.yml
> 🌱Bump golangci-lint to v1.63.4

- OWNERS_ALIASES
I've been following this repo, commenting on issues, reviewing various PRs and contributing bug fixes for a long time.
I have expertise around the Kube API space and in particular around the tooling for CRD generation that lives within this repository.
Figured it might be helpful to offer some review time to help alleviate some of the pressure on current maintainers.
>  🌱 Add JoelSpeed to reviewers

- pkg/webhook/testdata/invalid-admissionReviewVersionsRequired/manifests.yaml
- pkg/webhook/testdata/invalid-admissionReviewVersionsRequired/webhook.go
- pkg/webhook/testdata/invalid-multiple-webhookconfigurations/webhook.go
- pkg/webhook/testdata/invalid-path-and-url/webhook.go
- pkg/webhook/testdata/invalid-sideEffects/manifests.yaml
- pkg/webhook/testdata/invalid-sideEffects/webhook.go
- pkg/webhook/testdata/invalid-timeoutSeconds/manifests.yaml
- pkg/webhook/testdata/invalid-timeoutSeconds/webhook.go
- pkg/webhook/testdata/invalid-v1beta1NotSupported/manifests.yaml
- pkg/webhook/testdata/invalid-v1beta1NotSupported/webhook.go
- pkg/webhook/testdata/manifests.yaml
- pkg/webhook/testdata/valid-custom-name/manifests.yaml
- pkg/webhook/testdata/valid-custom-name/webhook.go
- pkg/webhook/testdata/valid-ordered/manifests.yaml
- pkg/webhook/testdata/valid-ordered/webhook.go
- pkg/webhook/testdata/valid-url/manifests.yaml
- pkg/webhook/testdata/valid-url/webhook.go
- pkg/webhook/testdata/valid/manifests.yaml
- pkg/webhook/testdata/valid/webhook.go
- pkg/webhook/testdata/webhook.go
No functional changes. The example code has `kubebuiler` in many places instead of `kubebuilder`. This fixes them.
Signed-off-by: David Xia <david@davidxia.com>
> :bug: fix minor typo in `kubebuilder`

- pkg/webhook/parser.go
- pkg/webhook/parser_integration_test.go
- pkg/webhook/testdata/valid-custom-service/cronjob_types.go
- pkg/webhook/testdata/valid-custom-service/manifests.yaml
- pkg/webhook/testdata/valid-custom-service/webhook.go
- pkg/webhook/zz_generated.markerhelp.go
Allow customizing the webhook K8s Service's name, namespace, and port.
Look for the new `serviceName`, `serviceNamespace`, and `servicePort` fields.
```
❯ GOBIN=(pwd)/bin go install ./cmd/*
❯ ./bin/controller-gen webhook -w
Webhook
+kubebuilder:webhook:admissionReviewVersions=<[]string>,failurePolicy=<string>,groups=<[]string>[,matchPolicy=<string>],mutating=<bool>,name=<string>[,path=<string>][,reinvocationPolicy=<string>],resources=<[]string>[,serviceName=<string>][,serviceNamespace=<string>][,servicePort=<int>][,sideEffects=<string>][,timeoutSeconds=<int>][,url=<string>],verbs=<[]string>,versions=<[]string>[,webhookVersions=<[]string>]  package  specifies how a webhook should be served.
...
```
contributes to #865
> ✨ Allow customizing generated webhook K8s Service

- pkg/crd/markers/validation.go
- pkg/crd/markers/zz_generated.markerhelp.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Adds a new field to the `+kubebuilder:validation:XValidation` marker to specify `optionalOldSelf`. Adding this configuration option allows writing validation rules that behave one way on create vs update. For example, allow setting a field if it is an update, but don't allow the field to be set at creation.
For more explicit information on the `optionalOldSelf` field for validation rules, see https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#field-optional-oldself
> :sparkles: markers: add support for optionalOldSelf in XValidation marker

- pkg/rbac/parser.go
- pkg/rbac/zz_generated.markerhelp.go
Before this change, the file name of the role/clusterrole generated from `+rbac` markers was hardcoded to `role.yaml`.
This change introduces a parameter `fileName` to the RBAC generator, so that one can do
```
controller-gen rbac:fileName=my-rbac-my-choice.yaml
```
and have the file be `my-rbac-my-choice.yaml` instead. (Given no specified `output` in the above example, the full path of the output file will be `/config/rbac/my-rbac-my-choice.yaml`.)
This is useful e.g. in cases where the target directory structure is not the standard Kustomize-packaged Kubebuilder one, but instead e.g. a Helm chart where multiple sources of information may contribute to the final set of files.
> :sparkles: Parametrize filename for generated RBAC

- pkg/applyconfiguration/applyconfiguration_integration_test.go
- pkg/applyconfiguration/gen.go
- pkg/applyconfiguration/testdata/cronjob/api/v1/applyconfiguration/api/v1/cronjob.go
- pkg/applyconfiguration/testdata/cronjob/api/v1/applyconfiguration/utils.go
- pkg/applyconfiguration/testdata/cronjob/api/v1/cronjob_types.go
- pkg/crd/parser.go
- pkg/internal/crd/crd.go
The upstream generator we import infers the groupVersion from the package path: https://github.com/kubernetes/kubernetes/blob/b0b52f4fb29223f829b50ae58323c20a7764dfc9/staging/src/k8s.io/code-generator/cmd/applyconfiguration-gen/generators/targets.go#L263
The path might not be reflective of the groupVersion, so use the override mechanism: https://github.com/kubernetes/kubernetes/blob/b0b52f4fb29223f829b50ae58323c20a7764dfc9/staging/src/k8s.io/code-generator/cmd/applyconfiguration-gen/generators/targets.go#L270
Fixes https://github.com/kubernetes-sigs/controller-tools/issues/1194
> :bug: Applyconfiguration: Use correct groupVersion

- pkg/applyconfiguration/applyconfiguration_integration_test.go
- pkg/applyconfiguration/gen.go
It seems the markers collector will only collect markers which have been explicitly registered to the markers registry. Since `groupName` is never registered, it always fails with
```
could not infer groupVersion for package - Is the `// +groupName` marker set?
Error: not all generators ran successfully
run `controller-gen applyconfiguration paths=./api/v1beta1/ -w` to see all available markers, or `controller-gen applyconfiguration paths=./api/v1beta1/ -h` for usage
```
because the marker will not be in the map of markers despite the marker being set on the package.
This registers the CRD markers (`groupName`, `versionName`, etc) so they can be collected and used to infer the group version.
Fixes #1218
> 🐛 Applyconfiguration: register CRD markers

- pkg/crd/markers/validation.go
- pkg/crd/testdata/oneof/types.go
- pkg/crd/testdata/testdata.kubebuilder.io_oneofs.yaml
Currently, if both XValidation and AtMostOneOf/ExactlyOneOf constraints are specified, the ordering of CEL rules can change due to both sets of markers have the same apply priority. This change ensures that OneOf markers always run **after** XValidation markers. Without this, the generated CRD can change without any API changes, which is undesirable.
> 🐛markers/OneOf: make order deterministic relative to XValidation

- OWNERS_ALIASES
Sync after https://github.com/kubernetes/org/pull/5691
> 📖 Sync admins & maintainers with kubernetes/org

- .golangci.yml
ref: https://github.com/kubernetes-sigs/controller-runtime/pull/3263
Sync `.golangci.yaml` from controller-runtime. Keep configuration consistent.
> 🌱chore: Sync `.golangci.yaml` from controller-runtime

- pkg/crd/schema.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
- pkg/crd/testdata/testdata.kubebuilder.io_jobs.yaml
> 🐛 Stop setting invalid formats int32/int64 for integer types

- pkg/crd/schema.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
- pkg/crd/testdata/testdata.kubebuilder.io_jobs.yaml
This reverts commit 02ea9af67be0303d83147446e7386cbe98c10e08.
The v1.34.0 kube-apiserver returns `"unrecognized format \"int64\""` warnings. We initially thought this was intended and adjusted controller-gen accordingly (https://github.com/kubernetes-sigs/controller-tools/pull/1274)
Turns out it was not (https://github.com/kubernetes/kubernetes/issues/133880), so now reverting the previous change.
> 🐛 Revert "Stop setting invalid formats int32/int64 for integer types"

- pkg/crd/markers/validation.go
- pkg/crd/testdata/cronjob_types.go
- pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
We use types to reduce duplication and increase the consistency of our CRDs. This allows the `+kubebuilder:title` marker to be set on a type as well as a field.
```go
// +kubebuilder:title="Secret Name"
// +kubebuilder:validation:MinLength=1
// +kubebuilder:validation:MaxLength=253
type SecretName = string
```
Fixes: #883
See: #1175
> ✨ Allow title to be set on a type
